#+title: WSL 2 configuration
#+author: Aaron Kunde
#+email: aaron.kunde@web.de
Settings and descriptions of the WSL 2 configuration.

This project describes the configuration of the WSL 2 and scripts to set up this configuration.

* Prerequisites
It is assumed, that an official [[https://github.com/microsoft/WSL/releases][release]] is initially installed and the default user is not /root/. This configuration is tested on a Debian (bookworm) distribution with the WSL version 2.4.11.0. This version should also support [[https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][Linux GUI apps]].

* Configure WSL Debian
To automate the configuration the script [[file:bin/config_debian.sh][config_debian.sh]] includes all necessary steps, which has to be executed by root.
#+begin_src shell :tangle bin/config_debian.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<apt_disable_recs>>
  <<apt_add_non-free>>
  <<alternatives_set_editor>>
  <<locale_install_de>>

  <<apt_update>>
  <<install_global_base_software>>
  <<install_global_latex>>

  <<purge_docker_and_podman>>
  <<install_podman>>
  <<install_podman-compose>>
#+end_src

** Disable recommended packages
Regarding [[https://wiki.debian.org/ReduceDebian#Reconfigure_apt_so_that_it_does_not_install_additional_packages][Reduce Debian]], reconfigure /apt/ so that it does not install additional packages, by adding a new file ~/etc/apt/apt.conf.d/10get~:

#+name: apt_disable_recs
#+begin_src shell :dir /sudo:: :results silent
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10get
#+end_src

To verify, execution of
#+begin_src shell :results verbatim
  apt-config dump | grep -e 'APT::Install-'
#+end_src

should return:
: APT::Install-Recommends "0";
: APT::Install-Suggests "0";

** Add non-free packages
To install non-free packages (like /emacs-common-non-dfsg/), add a file ~/etc/apt/sources.list.d/debian.non-free.list~:
#+name: apt_add_non-free
#+begin_src shell :dir /sudo:: :results silent
  sed /etc/apt/sources.list -e \
      's/\(deb.* \)main/\1non-free non-free-firmware/' \
      | tee /etc/apt/sources.list.d/debian.non-free.list
#+end_src

and update APT by executing
#+name: apt_update
#+begin_src shell :dir /sudo:: :results silent
  apt-get update
#+end_src
afterwards.

** Set default editor
Based on  https://wiki.debian.org/TextEditor set the default editor globally to the already installed /vim.tiny/:
#+name: alternatives_set_editor
#+begin_src shell :dir /sudo:: :results silent
  update-alternatives --set editor /usr/bin/vim.tiny
#+end_src

To verify, execution of
#+begin_src shell :results verbatim
  update-alternatives --display editor | grep current
#+end_src

should result to:
:   link currently points to /usr/bin/vim.tiny

** Add needed locales
To use /de_DE.UTF-8/ in other programs, like Emacs, these additional locales must at least be installed, like it is described at https://wiki.debian.org/Locale:
#+name: locale_install_de
#+begin_src shell :dir /sudo:: :results verbatim
  sed -iorig -e 's/# de_DE\.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  locale-gen
#+end_src

** OPTIONAL: Set locale for scripts                                :optional:
Like it is described in the [[https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Locale-Environment-Variables.html][gettext manual]] and at https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do, scripts use the variable ~LC_ALL~, which should be set as a fallback. For now the default is /en_EN.UTF-8/ is used.

** Install global software
Install software for every day use:
#+name: install_global_base_software
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  aspell-de \
	  bash-completion \
	  ca-certificates \
	  curl \
	  dos2unix \
	  emacs \
	  emacs-common-non-dfsg \
	  file \
	  git \
	  gitk \
	  gnupg \
	  gnuplot \
	  man-db \
	  net-tools \
	  netcat-openbsd \
	  markdown \
	  openssh-client \
	  patch
#+end_src

Install packages for working with LaTeX. Emacs is already installed or will be as a dependency:
#+name: install_global_latex
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  auctex \
	  texlive-latex-recommended \
	  texlive-latex-extra \
	  texlive-plain-generic
#+end_src

** Activate systemd                                                :obsolete:
To use Podman or Docker properly, /systemctl/ is needed. Therefore the [[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/][systemd support on WSL]] has to be activated. Because in newer versions (WSL version: 2.3.26.0) this is already done, the following steps should not be needed:

1. Create a file in the WSL ~/etc/wsl.conf~, if not already exists:
#+begin_src shell :dir /sudo:: :results silent
  echo -e "[boot]\nsystemd=true" > /etc/wsl.conf
#+end_src

2. Restart WSL
#+begin_src powershell
  wsl --shutdown
#+end_src

3. To check, if ~systemctl~ works, executing
#+begin_src shell :results verbatim
  systemctl list-unit-files --type=service
#+end_src

should result in something like:
#+begin_example
  UNIT FILE                              STATE           PRESET
  apt-daily-upgrade.service              static          -
  ...
  x11-common.service                     masked          enabled

  115 unit files listed.
#+end_example

*Note*: To have systemctl working for non-root users, /dbus-user-session/ must be installed and running. It is not installed as default, but comes as a dependency of /podman/ or /gnupg/. After installation of /dbus-user-session/, it may be necessary to terminate WSL with:
#+begin_src powershell
  wsl --terminate <<Distro>>
#+end_src

** Install Podman 4.3.1

*** Deinstall old versions
If an older version of podman or docker is installed, it should be purged:
#+name: purge_docker_and_podman
#+begin_src shell :dir /sudo:: :results silent
  apt-get purge -y \
	  docker \
	  docker-compose \
	  containernetworking-plugins \
	  podman \
	  podman-compose
  apt-get autopurge -y
#+end_src

*** Install Podman
Based on https://podman.io/docs/installation, install podman and its necessary dependencies:
#+name: install_podman
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman
  apt-get install --mark-auto \
	  uidmap \
	  slirp4netns
#+end_src

*** Verify
Based on https://docs.podman.io/en/latest/Introduction.html, execution of
#+begin_src shell :results verbatim
  podman run docker.io/library/busybox echo "hey there"
#+end_src

should restult in:
: hey there

** Use docker-compose files
There are several alternatives to use Docker Compose files together with Podman:
1. [[* Use Podman Compose 1.0.3][Use Podman Compose]]
2. [[* OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman][Use Docker Compose]]
3. Use Podman Pods and generate Kubernetes files, like described on https://www.redhat.com/en/blog/compose-podman-pods

*** Use Podman Compose 1.0.3
This is based on https://github.com/containers/podman-compose. Since this is the simpliest and nearest method to Podman, it is also the preferred one, even if it is not fully compatible with all features of Docker Compose.
To Install Podman Compose, just execute:
#+name: install_podman-compose
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman-compose
#+end_src

*** OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman       :optional:
Based on  https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/, this setup can be used to use the ~docker-compose~ command. This may be necessary, if features unsupported by ~podman-compose~ are needed. This may lead to side-effects with networking.

1. Verify, that Podman socket is active by executing
   #+begin_src shell :results verbatim
      systemctl status podman.socket
   #+end_src

   which should result to something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/lib/systemd/system/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Mon 2025-02-17 08:59:30 CET; 2 days ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/podman/podman.sock (Stream)
	  CGroup: /system.slice/podman.socket

     Feb 17 08:59:30 6RBVJR3 systemd[1]: Listening on podman.socket - Podman API Socket.
   #+end_example

2. Install /docker-compose/ and /podman-docker/ as dependency:
   #+begin_src shell :dir /sudo:: :results silent
       apt-get install -y docker-compose
       apt-get install -y --mark-auto podman-docker
   #+end_src

3. Verify the communication with the Docker socket by executing:
   #+begin_src shell :dir /sudo:: :results verbatim
     curl -H "Content-Type: application/json" --unix-socket /var/run/docker.sock http://localhost/_ping
   #+end_src

   This should result to:
   : OK

4. Start Podman socket for regular user:
   #+begin_src shell :results silent
     systemctl --user enable podman.socket
     systemctl --user start podman.socket
   #+end_src

   Verify the creation of the socket, by executing
   #+begin_src shell :results verbatim
     systemctl --user status podman.socket
   #+end_src

   which should return something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Wed 2025-02-19 17:10:37 CET; 7s ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/user/1000/podman/podman.sock (Stream)
	  CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

     Feb 19 17:10:37 6RBVJR3 systemd[205]: Listening on podman.socket - Podman API Socket.
   #+end_example

5. Verify by executing ~docker-compose~ after setting the environment variable ~DOCKER_HOST~
   #+begin_src shell
     DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock docker-compose up
   #+end_src

*** TODO Needed for init containers
#+begin_src shell
  sudo apt-get install catatonit
#+end_src

*** TODO Later dependencies for podman
#+begin_src shell
  netavark aardvark-dns
  buildah
  +dbus-user-session+
  fuse-overlayfs
  catatonit
#+end_src

*** TODO Stuff to docker-compose
https://github.com/containers/podman-compose/blob/devel/README.md
https://docs.oracle.com/en/learn/podman-compose/index.html
https://github.com/containers/podman/issues/13396
https://www.redhat.com/sysadmin/container-networking-podman
https://github.com/containers/podman/pull/17578
https://github.com/containers/podman/issues/17499
https://github.com/containers/podman/issues/17731
Wird benötigt, wenn Features von docker-compose benötigt werden, die nicht von Podman compose unterstützt werden. Kann aber zu Nebeneffekten bei Netzwerken führen, da hierduch CNI als Default-Netzwerk-Backend gesetzt wird, was wiederum nicht dem Podman-Reinen default von netavark.


*** OBSOLETE: Setup for Debian WSL2 Podman 3.x
https://gist.github.com/GiovanniGrieco/94ab72099fa35bc307fda0e36b88f1bd
#+begin_src sh
  mkdir -p $HOME/.config/containers/ &&
  sed -e 's/.*cgroup_manager =.*/cgroup_manager = "cgroupfs"/' /usr/share/containers/containers.conf | sed -e 's/.*events_logger = .*/events_logger = "file"/' > ~/.config/containers/containers.conf
#+end_src



*** Networking-Probleme
https://github.com/containers/podman-compose/issues/541#issuecomment-1221417067

* Configure user environment
#+begin_src shell :tangle bin/config_user.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<gpg_add_tty>>
  <<ssh_add_start_ssh-agent_to_profile>>
  <<ssh_add_config>>
#+end_src

** Configure GPG
To enable signing of git commits using the commandline, add the following configuration to ~$HOME/.profile~ like it is described in the [[https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html#Invoking-GPG_002dAGENT][GnuPG manual:]]
#+name: gpg_add_tty
#+begin_src shell :results silent
  echo -e '\nexport GPG_TTY=$(tty)' >> ~/.profile
#+end_src

** Configure SSH agent
Based on https://www.ssh.com/academy/ssh/agent, the SSH agent should be either started by adding
#+begin_src shell
  eval $(ssh-agent)
#+end_src
to ~$HOME/.profile~ or by using the provided ~/etc/X11/Xsession.d/90x11-common_ssh-agent~ for a system-wide start. Both ways are not suitable for WSL, because the first creates a new agent for each terminal and the latter does not work, because ~Xsession~ is never executed.

Therefore, based on https://superuser.com/questions/1808572/how-to-automate-starting-the-ssh-agent-and-adding-my-keys-in-wsl2-for-windows, the following lines are added to ~$HOME/profile~
#+begin_src shell :tangle bin/start_ssh-agent.sh :mkdirp yes :noweb yes
  SSH_AGENT_ENV_FILE=.ssh/agent-env

  if [ -z "$(pidof ssh-agent)" ]; then
      ssh-agent | head -n2 > $SSH_AGENT_ENV_FILE
  fi
  if [ -f $SSH_AGENT_ENV_FILE ]; then
      eval $(cat $SSH_AGENT_ENV_FILE)
  fi
#+end_src

by executing:
#+name: ssh_add_start_ssh-agent_to_profile
#+begin_src shell :results silent
  echo '' >> ~/.profile
  cat bin/start_ssh-agent.sh >> ~/.profile
#+end_src

Another option could be, to use /systemd/ as user by by executing:
#+begin_src shell
  systemctl --user start ssh-agent
#+end_src
But this is not a suitable solution, because it does not set the necessary environment variables ~SSH_AUTH_SOCK~ in the current or a new terminal.

To always instruct a running SSH agent to add keys, add the following configuration setting to your local ssh config file ~$HOME/.ssh/config~ before any ~Host~ or ~Match~ restrictions. Otherwise it will only be activated for this condition. Here it is set as the first option:
#+name: ssh_add_config
#+begin_src shell :results silent
  echo 'AddKeysToAgent yes' > ~/.ssh/config
#+end_src
** TODO Basic SD
#+begin_src

#+end_src
#+begin_src shell :results verbatim
apt-cache show \


	     xz-utils \

	     unzip 
#+end_src

** TODO Install user software
*** TODO Install asdf

** TODO Weiteres für Entwicklung
#+begin_src shell
  apt-mark showauto \


	 gimp \
	 # To prevent error: https://stackoverflow.com/questions/17355863/cant-find-install-libxtst-so-6 \
	 libxtst6 \
	 # Maybe because of plantuml
	 graphviz \
	 bzip2 \

	 # for IntelliJ \
	 libdrm2 \
	 libgbm1 \
	 # To prevent error messages. See: https://gist.github.com/jeffcogswell/62395900725acef1c0a5a608f7eb7a05 \
	 at-spi2-core \
	 # To prevent error messages. See: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo \
	 libgl1-mesa-glx \

#+end_src

#+RESULTS:




