#+title: WSL 2 configuration
#+author: Aaron Kunde
#+email: aaron.kunde@web.de
Settings and descriptions of the WSL 2 configuration.

This project describes the configuration of the WSL 2 and scripts to set up this configuration.

* Prerequisites
It is assumed, that an official [[https://github.com/microsoft/WSL/releases][release]] is initially installed and the default user is not /root/. This configuration is tested on a Debian (bookworm) distribution with the WSL version 2.4.11.0. This version should also support [[https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][Linux GUI apps]].

* Configure WSL Debian
To automate the configuration the script [[file:bin/config_debian.sh][config_debian.sh]] includes all necessary steps, which has to be executed as /root/.
#+begin_src shell :tangle bin/config_debian.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<apt_disable_recs>>
  <<apt_add_non-free>>
  <<alternatives_set_editor>>
  <<locale_install_de>>

  <<apt_update>>
  <<install_global_base_software>>

  <<latex_install>>

  <<podman_purge_old_versions>>
  <<podman_install>>
  <<podman_install_global_requirements>>
  <<podman_install_rootless_requirements>>
  <<podman-compose_install>>

  <<nct_add_gpg-key>>
  <<nct_add_apt-sources>>
  <<apt_update>>
  <<nct_install>>
  <<nct_configure_podman>>

  <<python_install_requirements>>

  <<gradle_install_requirements>>

  <<idea_install_requirements>>

  <<vscode_install_requirements>>

  <<plantuml_install_requirements>>
#+end_src

** Disable recommended packages
Regarding [[https://wiki.debian.org/ReduceDebian#Reconfigure_apt_so_that_it_does_not_install_additional_packages][Reduce Debian]], configure APT to not install additional packages. Add a new file ~/etc/apt/apt.conf.d/10get~:
#+name: apt_disable_recs
#+begin_src shell :dir /sudo:: :results silent
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10get
#+end_src

To verify, execute:
#+begin_src shell :results verbatim
  apt-config dump | grep -e 'APT::Install-'
#+end_src

This should result to:
: APT::Install-Recommends "0";
: APT::Install-Suggests "0";

** Add non-free packages
To install non-free packages, like [[https://packages.debian.org/bookworm/emacs-common-non-dfsg][emacs-common-non-dfsg]]:

1. Add a file ~/etc/apt/sources.list.d/debian.non-free.list~:
   #+name: apt_add_non-free
   #+begin_src shell :dir /sudo:: :results silent
     sed /etc/apt/sources.list -e \
	 's/\(deb.* \)main/\1non-free non-free-firmware/' \
	 | tee /etc/apt/sources.list.d/debian.non-free.list
   #+end_src

2. Update APT:
   #+name: apt_update
   #+begin_src shell :dir /sudo:: :results silent
     apt-get update
   #+end_src

** Set default editor
Based on  https://wiki.debian.org/TextEditor set the default editor globally to the already installed [[https://packages.debian.org/bookworm/vim-tiny][vim.tiny]]:
#+name: alternatives_set_editor
#+begin_src shell :dir /sudo:: :results silent
  update-alternatives --set editor /usr/bin/vim.tiny
#+end_src

To verify, execute:
#+begin_src shell :results verbatim
  update-alternatives --display editor | grep current
#+end_src

This should result to:
:   link currently points to /usr/bin/vim.tiny

** Add needed locales
To use the additional locale /de_DE.UTF-8/ in other programs (like Emacs), it must be installed, like it is described at https://wiki.debian.org/Locale:
#+name: locale_install_de
#+begin_src shell :dir /sudo:: :results verbatim
  sed -iorig -e 's/# de_DE\.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  locale-gen
#+end_src

** OPTIONAL: Set locale for scripts                                :optional:
Like it is described in the [[https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Locale-Environment-Variables.html][gettext manual]] and at https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do, scripts use the variable ~LC_ALL~, which should be set as a fallback. For now the default is /en_EN.UTF-8/ is used.

** Install global software
Install software for every day use:
#+name: install_global_base_software
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  aspell-de \
	  bash-completion \
	  btop \
	  ca-certificates \
	  curl \
	  dos2unix \
	  emacs \
	  emacs-common-non-dfsg \
	  file \
	  git \
	  gitk \
	  gnupg \
	  gnuplot \
	  htop \
	  lsof \
	  man-db \
	  net-tools \
	  netcat-openbsd \
	  markdown \
	  openssh-client \
	  patch \
	  xz-utils
#+end_src

Install packages for working with LaTeX. Emacs is already installed or will be as a dependency:
#+name: latex_install
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  auctex \
	  texlive-latex-recommended \
	  texlive-latex-extra \
	  texlive-plain-generic
#+end_src

** Activate systemd                                                :obsolete:
To use Podman or Docker properly, [[https://packages.debian.org/bookworm/systemctl][systemctl]] is needed. Therefore the [[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/][systemd support on WSL]] has to be activated. Because in newer versions (WSL version: 2.3.26.0) this is already done, the following steps should not be needed:

1. Create a file ~/etc/wsl.conf~, if not already exists:
#+begin_src shell :dir /sudo:: :results silent
  echo -e "[boot]\nsystemd=true" > /etc/wsl.conf
#+end_src

2. Restart WSL:
#+begin_src powershell
  wsl --shutdown
#+end_src

3. To check, if ~systemctl~ works, execute:
#+begin_src shell :results verbatim
  systemctl list-unit-files --type=service
#+end_src

This should result to something like:
#+begin_example
  UNIT FILE                              STATE           PRESET
  apt-daily-upgrade.service              static          -
  ...
  x11-common.service                     masked          enabled

  115 unit files listed.
#+end_example

*Note*: To have systemctl working for non-root users, [[https://packages.debian.org/bookworm/dbus-user-session][dbus-user-session]] must be installed and running. It is not installed as default, but comes as a dependency of [[https://packages.debian.org/bookworm/podman][podman]] or [[https://packages.debian.org/bookworm/gnupg][gnupg]]. After installation of dbus-user-session, it may be necessary to terminate WSL with:
#+begin_src powershell
  wsl --terminate <<Distro>>
#+end_src

** Install Podman 4.3.1
The current version of Podman in the current Debian stable distribution is 4.3.1.

*** Deinstall old versions
Based on the [[https://docs.docker.com/engine/install/debian/][Docker installation manual]], uninstall old versions of docker and podman and everything, which might have been installed before:
#+name: podman_purge_old_versions
#+begin_src shell :dir /sudo:: :results silent
  apt-get purge -y \
	  ,*docker* \
	  docker-compose \
	  ,*container* \
	  ,*podman* \
	  podman-compose
  apt-get autopurge -y

  rm -rf /var/lib/docker \
     /var/lib/containerd \
     /etc/apt/sources.list.d/docker.list \
     /etc/apt/keyrings/docker.asc \
     /etc/containers
#+end_src

*** Install Podman
Based on https://podman.io/docs/installation, install [[https://packages.debian.org/bookworm/podman][podman]] and its necessary dependencies:
#+name: podman_install
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman
#+end_src

The additional packages [[https://packages.debian.org/bookworm/uidmap][uidmap]] and [[https://packages.debian.org/bookworm/slirp4netns][slirp4netns]] are required, to run podman without errors. The packages [[https://packages.debian.org/bookworm/aardvark-dns][aardvark-dns]] and its dependency [[https://packages.debian.org/bookworm/netavark][netavark]] are necessary to let podman container communicate in their own networks:
#+name: podman_install_global_requirements
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y --mark-auto \
	  uidmap \
	  slirp4netns \
	  aardvark-dns
#+end_src

*Note*: According to https://podman.io/docs/installation, ~slirp4netns~ is not needed in newer versions of Podman anymore.

*** Install dependencies for rootless
Based on the [[https://github.com/containers/podman/blob/v4.3.1/docs/tutorials/rootless_tutorial.md][Podman rootless tutorial]], the package [[https://packages.debian.org/bookworm/fuse-overlayfs][fuse-overlayfs]] must be installed:
#+name: podman_install_rootless_requirements
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y --mark-auto fuse-overlayfs
#+end_src

This has no effect, which can be verified with:
#+begin_src shell
  podman info | grep graphDriverName
#+end_src

Ususally this results to:
: graphDriverName: vfs

*Note*: Accoring to https://www.redhat.com/en/blog/podman-rootless-overlay, fuse-overlayfs is not needed in newer versions of Podman anymore.

** Use docker-compose files
There are several alternatives to use Docker Compose files together with Podman:
1. [[* Use Podman Compose 1.0.3][Use Podman Compose]]
2. [[* OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman][Use Docker Compose]]
3. Use Podman Pods and generate Kubernetes files, like described on https://www.redhat.com/en/blog/compose-podman-pods

*** Use Podman Compose 1.0.3
This is based on https://github.com/containers/podman-compose. Since this is the simplest and nearest method to Podman, it is also the preferred one, even if it is not fully compatible with all features of Docker Compose.
To install [[https://packages.debian.org/bookworm/podman-compose][podman-compose]], execute:
#+name: podman-compose_install
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman-compose
#+end_src

*** OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman       :optional:
Based on  https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/, this setup can be used to use the ~docker-compose~ command. This may be necessary, if features unsupported by Podman Compose are needed. This may lead to side-effects with networking.

1. Verify, that Podman socket is active:
   #+begin_src shell :results verbatim
      systemctl status podman.socket
   #+end_src

   This should result to something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/lib/systemd/system/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Mon 2025-02-17 08:59:30 CET; 2 days ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/podman/podman.sock (Stream)
	  CGroup: /system.slice/podman.socket

     Feb 17 08:59:30 6RBVJR3 systemd[1]: Listening on podman.socket - Podman API Socket.
   #+end_example

2. Install [[https://packages.debian.org/bookworm/docker-compose][docker-compose]] and [[https://packages.debian.org/bookworm/podman-docker][podman-docker]] as dependency:
   #+begin_src shell :dir /sudo:: :results silent
       apt-get install -y docker-compose
       apt-get install -y --mark-auto podman-docker
   #+end_src

3. Verify the communication with the Docker socket:
   #+begin_src shell :dir /sudo:: :results verbatim
     curl -H "Content-Type: application/json" --unix-socket /var/run/docker.sock http://localhost/_ping
   #+end_src

   This should result to:
   : OK

4. Start Podman socket for regular user:
   #+begin_src shell :results silent
     systemctl --user enable podman.socket
     systemctl --user start podman.socket
   #+end_src

   Verify the creation of the socket:
   #+begin_src shell :results verbatim
     systemctl --user status podman.socket
   #+end_src

   This should return something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Wed 2025-02-19 17:10:37 CET; 7s ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/user/1000/podman/podman.sock (Stream)
	  CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

     Feb 19 17:10:37 6RBVJR3 systemd[205]: Listening on podman.socket - Podman API Socket.
   #+end_example

5. Verify by executing ~docker-compose~ after setting the environment variable ~DOCKER_HOST~
   #+begin_src shell
     DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock docker-compose up
   #+end_src

*** TODO Needed for init containers
#+begin_src shell
  sudo apt-get install catatonit
#+end_src

*** TODO Later dependencies for podman
#+begin_src shell
  buildah
  +dbus-user-session+
  catatonit
#+end_src

*** TODO Stuff to docker-compose
https://github.com/containers/podman-compose/blob/devel/README.md
https://docs.oracle.com/en/learn/podman-compose/index.html
https://github.com/containers/podman/issues/13396
https://www.redhat.com/sysadmin/container-networking-podman
https://github.com/containers/podman/pull/17578
https://github.com/containers/podman/issues/17499
https://github.com/containers/podman/issues/17731
Wird benötigt, wenn Features von docker-compose benötigt werden, die nicht von Podman compose unterstützt werden. Kann aber zu Nebeneffekten bei Netzwerken führen, da hierduch CNI als Default-Netzwerk-Backend gesetzt wird, was wiederum nicht dem Podman-Reinen default von netavark.

*** TODO Networking-Probleme
https://github.com/containers/podman-compose/issues/541#issuecomment-1221417067

** Add NVIDIA Container Toolkit
To give Podman containers access to the NVIDIA GPU, the [[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html][NVIDIA Container Toolkit]] must be installed, like described for the [[https://hub.docker.com/r/ollama/ollama][Ollama Docker image]]:

1. Download the GPG keys and add them to the keyring as ~/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg~:
   #+name: nct_add_gpg-key
   #+begin_src shell :results silent :dir /sudo::
     curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
	 | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
   #+end_src

2. Add the sources for the toolkit as ~/etc/apt/sources.list.d/nvidia-container-toolkit.list~ to APT:
   #+name: nct_add_apt-sources
   #+begin_src  shell :results silent :dir /sudo::
     curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
	 | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
	 | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
     apt-get install -y nvidia-container-toolkit
   #+end_src

3. Update APT:
   #+name: apt_update
   #+begin_src shell :dir /sudo:: :results silent
     apt-get update
   #+end_src

4. Install the toolkit:
   #+name: nct_install
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y nvidia-container-toolkit
   #+end_src

   Verify the installation:
   #+begin_src shell
     nvidia-ctk cdi list
   #+end_src

   This should result to:
   : nvidia.com/gpu=all

5. Configure Podman by using [[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html][CDI support]] and adding ~/etc/cdi/nvidia.yaml~:
   #+name: nct_configure_podman
   #+begin_src shell :results silen :dir /sudo::
     nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
   #+end_src

   Verify, by executing ~nvidia-smi~ inside a container:
   #+begin_src shell
     podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L
   #+end_src

   This should result to:
   : GPU 0: NVIDIA RTX A1000 Laptop GPU (UUID: GPU-67d3f5e6-b6f8-ecd8-b874-106d2fc38caf)

* Configure user environment
The script [[file:bin/config_user.sh][config_user.sh]] includes all necessary steps, to setup the user environment. It has to be executed as a non-root user. The path ~$HOME/.local/bin~ is only added to ~$PATH~, if the directory exists. Because this is not the case, when executing this script initially, ~$HOME/.local/bin~ is added for this script execution explicitly:
#+begin_src shell :tangle bin/config_user.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  if [ $(id -u) -eq 0 ]; then
      echo "You should not be root"
      exit 1
  fi

  cp /etc/skel/.profile ~
  cp /etc/skel/.bashrc ~

  PATH="$HOME/.local/bin:$PATH"

  <<disable_at-spi2-error>>

  <<gpg_add_tty>>

  <<ssh_add_start_ssh-agent_to_profile>>
  <<ssh_add_config>>

  <<podman_enable_overlayfs>>

  <<firefox_create_link>>

  <<asdf_download>>
  <<asdf_verify>>
  <<asdf_extract>>
  <<asdf_add_shims>>
  <<asdf_add_shell_completions>>
  <<asdf_create_config>>

  <<kubectl_install>>
  <<kubectl_add_shell_completions>>

  <<helm_install>>
  <<helm_add_shell_completions>>

  <<make_install>>

  <<shellcheck_install>>

  <<python_install>>

  <<azure-cli_set_global_python_version>>
  <<azure-cli_install>>

  <<golang_install>>

  <<java_install>>

  <<maven_install>>

  <<gradle_install>>

  <<nodejs_install>>

  <<pnpm_install>>

  <<idea_download>>
  <<idea_verify>>
  <<idea_extract>>
  <<idea_create_link>>
  <<idea_install_nodejs>>

  <<dbeaver_download>>
  <<dbeaver_verify>>
  <<dbeaver_extract>>
  <<dbeaver_create_link>>

  <<vscode_download>>
  <<vscode_verify>>
  <<vscode_extract>>
  <<vscode_create_link>>

  <<plantuml_download>>
  <<plantuml_verify>>
  <<plantuml_remove_signature>>
  <<plantuml_create_link>>
#+end_src

** Disable AP-SPI warning message
GTK applications display the following error message, if the package [[https://packages.debian.org/at-spi2-core][at-spi2-core]] is not installed:
: ... dbind-WARNING ... AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Since no accessibility is needed the package is not installed. The error message is disabled by setting the environment variable ~NO_AT_BRIDGE=1~ in ~$HOME/.profile~:
#+name: disable_at-spi2-error
#+begin_src shell :results silent
  echo '\nexport NO_AT_BRIDGE=1' >> ~/.profile
#+end_src

** Configure GPG
To enable signing of git commits using the commandline, add the following configuration to ~$HOME/.profile~ like it is described in the [[https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html#Invoking-GPG_002dAGENT][GnuPG manual:]]
#+name: gpg_add_tty
#+begin_src shell :results silent
  echo '\nexport GPG_TTY=$(tty)' >> ~/.profile
#+end_src

** Configure SSH agent
Based on https://www.ssh.com/academy/ssh/agent, the SSH agent should be either started by adding
#+begin_src shell
  eval $(ssh-agent)
#+end_src
to ~$HOME/.profile~ or by using the provided ~/etc/X11/Xsession.d/90x11-common_ssh-agent~ for a system-wide start. Both ways are not suitable for WSL, because the first creates a new agent for each terminal and the latter does not work, because ~Xsession~ is never executed.

Therefore, based on https://superuser.com/questions/1808572/how-to-automate-starting-the-ssh-agent-and-adding-my-keys-in-wsl2-for-windows, the following lines are added to ~$HOME/profile~
#+name: start_ssh-agent.sh
#+begin_src shell
  SSH_AGENT_ENV_FILE=~/.ssh/agent-env

  if [ -z "$(pidof ssh-agent)" ]; then
      ssh-agent | head -n2 > $SSH_AGENT_ENV_FILE
  fi
  if [ -f $SSH_AGENT_ENV_FILE ]; then
      eval $(cat $SSH_AGENT_ENV_FILE)
  fi
#+end_src

by executing:
#+name: ssh_add_start_ssh-agent_to_profile
#+begin_src shell :noweb yes :exports none :results silent
  cat <<'EOF' >> ~/.profile

  <<start_ssh-agent.sh>>
  EOF
#+end_src

Another option could be, to use [[https://packages.debian.org/bookworm/systemd][systemd]] as user by by executing:
#+begin_src shell
  systemctl --user start ssh-agent
#+end_src
But this is not a suitable solution, because it does not set the necessary environment variables ~SSH_AUTH_SOCK~ in the current or a new terminal.

To always instruct a running SSH agent to add keys, add the following configuration setting to your local ssh config file ~$HOME/.ssh/config~ before any ~Host~ or ~Match~ restrictions. Otherwise it will only be activated for this condition. Here it is set as the first option:
#+name: ssh_add_config
#+begin_src shell :results silent
  mkdir -p ~/.ssh
  echo 'AddKeysToAgent yes' > ~/.ssh/config
#+end_src

** Configure Podman
According to the [[https://github.com/containers/podman/blob/v4.3.1/docs/tutorials/rootless_tutorial.md][Podman rootless tutorial]], [[https://packages.debian.org/bookworm/fuse-overlayfs][fuse-overlayfs]] should be installed and used as filesystem for rootless mode. To enable [[https://packages.debian.org/bookworm/fuse-overlayfs][fuse-overlayfs]], remove an already existing ~$HOME/.local/share/containers/storage/libpod/bolt_state.db~ and add a configuration file ~$HOME/.config/containers/storage.conf~ with the following entries
#+name: podman_storage.conf
#+begin_src conf
  [storage]
    driver = "overlay"

  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
#+end_src

by executing:
#+name: podman_enable_overlayfs
#+begin_src shell :noweb yes :exports none :results silent
  rm -f ~/.local/share/containers/storage/libpod/bolt_state.db
  mkdir -p ~/.config/containers
  cat <<EOF > ~/.config/containers/storage.conf
  <<podman_storage.conf>>
  EOF
#+end_src

After that, executing
#+begin_src shell
  podman info | grep graphDriverName
#+end_src

should results to:
: graphDriverName: overlay

Based on https://docs.podman.io/en/latest/Introduction.html, execution of
#+begin_src shell :results verbatim
  podman run docker.io/library/busybox echo "hey there"
#+end_src

should restult in:
: hey there

** Create link to Firefox
To use the Firefox, which is installed on the host system, create the following link in =~/.local/bin/=:
#+name: firefox_create_link
#+begin_src shell
  mkdir -p ~/.local/bin
  ln -fs "/mnt/c/Users/$USER/AppData/Local/Microsoft/WindowsApps/firefox.exe" \
     ~/.local/bin/firefox
#+end_src

** Install asdf
Based on [[https://asdf-vm.com/guide/getting-started.html][asdf Getting started]] -> /Download Pre-compiled binary/:

1. Download latest release files from https://github.com/asdf-vm/asdf/releases:
   #+name: asdf_download
   #+begin_src shell :results silent
     ASDF_VERSION=v0.16.4
     ASDF_INSTALLATION_FILE=asdf-$ASDF_VERSION-linux-amd64.tar.gz
     curl -L -O --output-dir /tmp \
	  "https://github.com/asdf-vm/asdf/releases/download/$ASDF_VERSION/$ASDF_INSTALLATION_FILE{,.md5}"
   #+end_src

2. Verify checksum:
   #+name: asdf_verify
   #+begin_src shell :results silent
     grep $(md5sum /tmp/$ASDF_INSTALLATION_FILE | cut -d ' ' -f 1) \
	  /tmp/$ASDF_INSTALLATION_FILE.md5
   #+end_src

3. Extract binary:
   #+name: asdf_extract
   #+begin_src shell :results silent
     mkdir -p ~/.local/bin
     tar -C ~/.local/bin -x -f /tmp/$ASDF_INSTALLATION_FILE
   #+end_src

4. Verify installation. After relogin executing
   #+begin_src shell :results verbatim
     type -a asdf
   #+end_src

   should result to:
   : asdf is /home/kunde/.local/bin/asdf

5. The asdf shims directory must be added to ~PATH~ for the current and future sessions:
   #+name: asdf_add_shims
   #+begin_src shell :results silent
     PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
     echo '\nPATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"' >> ~/.profile
   #+end_src

6. To add shell completion, add the following line to ~$HOME/.bashrc~:
   #+name: asdf_add_shell_completions
   #+begin_src shell :results silent
     echo '\n. <(~/.local/bin/asdf completion bash)' >> ~/.bashrc
   #+end_src
   Since ~$HOME/.bashrc~ is sourced before ~$HOME/.local/bin~ is added to the ~$PATH~ in ~$HOME/.profile~, ~asdf~ cannot be called without prefix. So the explicit path to asdf is used.

** Install asdf (legacy)                                           :obsolete:
Based on [[https://asdf-vm.com/guide/getting-started-legacy.html][asdf Getting started (pre-0.16.0)]]:

1. Checkout latest release:
   #+begin_src shell :results silent
     git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.15.0
   #+end_src

2. Add script to ~$PATH~ and Bash completions:
   #+begin_src shell :results silent
     echo '\n. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
     echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc
  #+end_src

3. To take effect, relogin or create a new subshell

** Configure asdf
Create a configuration file ~$HOME/.asdfrc~, to support versions files used by other version managers:
   #+name: asdf_create_config
   #+begin_src shell
     echo 'legacy_version_file = yes' > ~/.asdfrc
   #+end_src

** Install kubectl
1. To install the latest version of [[https://kubernetes.io/docs/reference/kubectl/][kubectl]] using asdf, execute:
   #+name: kubectl_install
   #+begin_src shell :results silent
     asdf plugin add kubectl
     asdf install kubectl latest
     asdf set -u kubectl latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     kubectl version
   #+end_src

   Which should return something like:
   : Client Version: v1.32.1
   : Kustomize Version: v5.5.0
   : Server Version: v1.31.4+rke2r1

3. Install autocompletion for bash. Based on https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/, add a line to ~$HOME/.profile~:
   #+name: kubectl_add_shell_completions
   #+begin_src shell :results silent
     echo '\n. <(kubectl completion bash)' >> ~/.profile
   #+end_src
   Since ~$HOME/.bashrc~ is sourced before ~$HOME/.asdf/shims~ is added to the ~$PATH~ in ~$HOME/.profile~ and the shim ~$HOME/.asdf/shims/kubectl~ itself uses ~asdf~ without a prefix, the shim cannot be used within ~$HOME/.bashrc~. As a workaround, the completion is sourced in ~$HOME/.profile~, until the shims may be fixed.

** Install Helm
1. The ~latest~ version is currently not supported by the asdf plugin. Therefore, a specific version of [[https://helm.sh/][Helm]] is installed:
   #+name: helm_install
   #+begin_src shell :results silent
     asdf plugin add helm
     asdf install helm 3.17.1
     asdf set -u helm 3.17.1
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     helm version
   #+end_src

   Which should return something like:
   : version.BuildInfo{Version:"v3.17.1", GitCommit:"980d8ac1939e39138101364400756af2bdee1da5", GitTreeState:"clean", GoVersion:"go1.23.5"}

3. Install autocompletion for bash. Based on https://helm.sh/docs/helm/helm_completion_bash/#helm, add a line to ~$HOME/.profile~:
   #+name: helm_add_shell_completions
   #+begin_src shell :results silent
     echo '\n. <(helm completion bash)' >> ~/.profile
   #+end_src
   Since ~$HOME/.bashrc~ is sourced before ~$HOME/.asdf/shims~ is added to the ~$PATH~ in ~$HOME/.profile~ and the shim ~$HOME/.asdf/shims/helm~ itself uses ~asdf~ without a prefix, the shim cannot be used within ~$HOME/.bashrc~. As a workaround, the completion is sourced in ~$HOME/.profile~, until the shims may be fixed.

** Install make
1. To install the latest version of [[https://www.gnu.org/software/make/][GNU make]] using asdf, execute:
   #+name: make_install
   #+begin_src shell :results silent
     asdf plugin add make
     asdf install make latest
     asdf set -u make latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     make -v
   #+end_src

   Which should return something like:
   : GNU Make 4.4.1
   : Built for x86_64-pc-linux-gnu
   : Copyright (C) 1988-2023 Free Software Foundation, Inc.
   : License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
   : This is free software: you are free to change and redistribute it.
   : There is NO WARRANTY, to the extent permitted by law.

** Install ShellCheck
The actual used version of [[https://www.shellcheck.net/][ShellCheck]] is project specific and not set globally. It is determined locally by an existing ~.tool-versions~.

1. To add the ShellCheck asdf plugin, execute:
   #+name: shellcheck_install
   #+begin_src shell :results silent
     asdf plugin add shellcheck
   #+end_src

2. The desired version is then installed locally in the project:
   #+begin_src shell :results silent
     asdf install shellcheck latest
   #+end_src

3. Verify installation by executing:
   #+begin_src shell :results verbatim
     shellcheck --version
   #+end_src

   Which should return something like:
   : ShellCheck - shell script analysis tool
   : version: 0.10.0
   : license: GNU General Public License, version 3
   : website: https://www.shellcheck.net

** Install Python
The actual used version of [[https://www.python.org/][Python]] is project specific and not set globally. It is determined locally by an existing ~.tool-versions~.

1. Python needs some system-wide packages installed, which are described at https://github.com/pyenv/pyenv/wiki#suggested-build-environment:
   #+name: python_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y \
	     gcc \
	     zlib1g-dev \
	     libssl-dev
   #+end_src

   *Note*: These are the minimum required packages, to complete the installation. For later use, further packages may be needed.

2. Furthermore, [[* Install make][make]] needs to be installed, which can be done using asdf.

3. After that, Python can be installed using asdf, by adding the asdf plugin:
   #+name: python_install
   #+begin_src shell :results silent
     asdf plugin add python
   #+end_src

4. The desired version is then installed locally in the project:
   #+begin_src shell :results silent
     asdf install python latest
   #+end_src

5. Verify installation by executing:
   #+begin_src shell :results verbatim
     python --version
   #+end_src

   Which should return something like:
   : Python 3.10.11

** Install Azure CLI
1. [[https://learn.microsoft.com/en-us/cli/azure/][Azure CLI]], needs [[* Install Python 3.11][Python]], which is installed together with the Azure CLI. To complete the installation process, the python version must be set globally first:
   #+name: azure-cli_set_global_python_version
   #+begin_src shell :results silent
     asdf set -u python 3.10.11
   #+end_src

2. To install the latest version of Azure CLI and the necessary python version using asdf, execute:
   #+name: azure-cli_install
   #+begin_src shell :results silent
     asdf plugin add azure-cli
     asdf install azure-cli latest
     asdf set -u azure-cli latest
   #+end_src

3. Verify installation by executing:
   #+begin_src shell :results verbatim
     az version
   #+end_src

   Which should return something like:
   : {
   :   "azure-cli": "2.68.0",
   :   "azure-cli-core": "2.68.0",
   :   "azure-cli-telemetry": "1.1.0",
   :   "extensions": {}
   : }

** Install minikube                                                    :fail:
1. To install the latest version of [[https://minikube.sigs.k8s.io/][minikube]] using asdf, execute:
   #+name: minikube_install
   #+begin_src shell :results silent
     asdf plugin add minikube
     asdf install minikube latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     minikube version
   #+end_src

   Which should return something like
   #+begin_example
     No version is set for command minikube
     Consider adding one of the following versions in your config file at /home/kunde/.tool-versions
     minikube 1.35.0
   #+end_example

3. The actual used version of minikube is project specific and not set globally. It is determined locally by an existing ~.tool-versions~. To use latest minikube together with Podman rootless execute the following in the project:
   #+begin_src shell
     asdf set minikube latest
     minikube config set rootless true
   #+end_src

4. After that, minikube might be used in the project with:
   #+begin_src shell
     minikube start
   #+end_src

   *Note*: Actually minikube in combination with podman rootless and WSL 2 Debian does not work and leads to the folling errors and warnings:
   #+begin_example
     The minimum required version for podman is "4.9.0". your version is "4.3.1". minikube might not work. use at your own risk.
     ...
     stderr:
	     [WARNING Swap]: swap is supported for cgroup v2 only. The kubelet must be properly configured to use swap. Please refer to https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory, or disable swap on the node
	     [WARNING SystemVerification]: cgroups v1 support is in maintenance mode, please migrate to cgroups v2
	     [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
     error execution phase wait-control-plane: could not initialize a Kubernetes cluster
     ...
   #+end_example

** Install Go
The actual used version of [[https://go.dev/][Go]] is project specific and not set globally. It is determined locally by an existing ~go.mod~ or ~.tool-versions~.

1. To add the asdf plugin, execute:
   #+name: golang_install
   #+begin_src shell :results silent
     asdf plugin add golang
   #+end_src

2. The desired version is then installed locally in the project:
   #+begin_src shell :results silent
     asdf install golang latest
   #+end_src

3. Verify installation by executing:
   #+begin_src shell :results verbatim
     go version
   #+end_src

   Which should return something like:
   :  No version is set for command go
   :  Consider adding one of the following versions in your config file at /home/kunde/work/tst-keycloak/.tool-versions
   :  golang 1.24.0

** Install Java
The actual used version of [[https://www.java.com/][Java]] may be project specific. But at least one JRE is needed globally. So, one JDK is defined globally:

1. To install a version of Java using asdf, execute:
   #+name: java_install
   #+begin_src shell :results silent
     asdf plugin add java
     asdf install java temurin-21.0.5+11.0.LTS
     asdf set -u java temurin-21.0.5+11.0.LTS
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     java --version
   #+end_src

   Which should return to:
   : openjdk 21.0.5 2024-10-15 LTS
   : OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
   : OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

** Install Maven
The actual used version of [[https://maven.apache.org/][Maven]] may be project specific. But at least one version is needed globally. So, one Maven version is defined globally:

1. To add the Maven asdf plugin, execute:
   #+name: maven_install
   #+begin_src shell :results silent
     asdf plugin add maven
     asdf install maven latest
     asdf set -u maven latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     mvn --version
   #+end_src

   Which should return something like:
   : Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
   : Maven home: /home/kunde/.asdf/installs/maven/3.9.9
   : Java version: 21.0.5, vendor: Eclipse Adoptium, runtime: /home/kunde/.asdf/installs/java/temurin-21.0.5+11.0.LTS
   : Default locale: en_US, platform encoding: UTF-8
   : OS name: "linux", version: "5.15.167.4-microsoft-standard-wsl2", arch: "amd64", family: "unix"

** Install Gradle
The actual used version of [[https://gradle.org/][Gradle]] is project specific and not set globally. It is determined locally by an existing ~.tool-versions~.

1. To add the Gradle asdf plugin, execute:
   #+name: gradle_install
   #+begin_src shell :results silent
     asdf plugin add gradle
   #+end_src

2. unzip] must be installed first
   #+name: gradle_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y unzip
   #+end_src

3. The desired version is then installed locally in the project. The ~latest~ version is currently not supported by the asdf plugin. Therefore, a specific version must be installed:
   #+begin_src shell :results silent
     asdf install gradle 8.12
   #+end_src

4. Verify installation by executing:
   #+begin_src shell :results verbatim
     gradle --version &2>1
   #+end_src

   Which should result to something like:
   : gradle 8.12

** Install Node.js
The actual used version of [[https://nodejs.org/en][Node.js]] is project specific and not set globally. It is determined locally by an existing ~.nvwmrc~ or ~.tool-versions~.

1. To add the Node.js asdf plugin, execute:
   #+name: nodejs_install
   #+begin_src shell :results silent
     asdf plugin add nodejs
   #+end_src

2. The desired version is then installed locally in the project:
   #+begin_src shell :results silent
     asdf install nodejs
   #+end_src

3. Verify installation by executing:
   #+begin_src shell :results verbatim
     node --version
   #+end_src

   Which should return something like:
   : v22.14.0

** Install pnpm
The actual used version of [[https://pnpm.io/][pnpm]] is project specific and not set globally. It is determined locally by an existing ~.tool-versions~.

1. To add the pnpm asdf plugin, execute:
   #+name: pnpm_install
   #+begin_src shell :results silent
     asdf plugin add pnpm
   #+end_src

2. The desired version is then installed locally in the project. The version is usually defined in ~package.json~ and can be determein:
   #+begin_src shell :results silent
     asdf install pnpm $(grep pnpm@ package.json | cut -d'@' -f2 | tr -d '",')
     asdf set pnpm $(grep pnpm@ package.json | cut -d'@' -f2 | tr -d '",')
   #+end_src

3. Verify installation by executing:
   #+begin_src shell :results verbatim
     pnpm --version
   #+end_src

   Which should return something like:
   : 9.6.0

** Install DBeaver
1. Download latest release files from https://dbeaver.io/download/:
   #+name: dbeaver_download
   #+begin_src shell :results silent
     DBEAVER_VERSION=25.0.0
     DBEAVER_INSTALLATION_FILE=dbeaver-ce-$DBEAVER_VERSION-linux.gtk.x86_64.tar.gz
     curl -L -O --output-dir /tmp \
	  https://dbeaver.io/files/$DBEAVER_VERSION/$DBEAVER_INSTALLATION_FILE
     curl -L -O --output-dir /tmp \
	  https://dbeaver.io/files/$DBEAVER_VERSION/checksum/$DBEAVER_INSTALLATION_FILE.sha256
   #+end_src

2. Verify checksum:
   #+name: dbeaver_verify
   #+begin_src shell :results silent
     grep $(sha256sum /tmp/$DBEAVER_INSTALLATION_FILE | cut -d ' ' -f 1) \
	  /tmp/$DBEAVER_INSTALLATION_FILE.sha256
   #+end_src

3. Extract binary:
   #+name: dbeaver_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$DBEAVER_INSTALLATION_FILE
   #+end_src

4. Create link:
   #+name: dbeaver_create_link
   #+begin_src shell :results silent
     mkdir -p ~/opt
     ln -s ~/opt/dbeaver/dbeaver ~/.local/bin/dbeaver
   #+end_src

** Install IntelliJ
1. Install necessary prerequisites for different features:
   #+name: idea_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y \
	     libxtst6 \
	     libgbm1 libglx-mesa0
   #+end_src
   - [[https://packages.debian.org/bookworm/libxtst6][libxtst6]] needs to be installed, to preven the following error:
     : libXtst.so.6: cannot open shared object file: No such file or directory
   - [[https://packages.debian.org/bookworm/libgbm1][libgbm1]] and [[https://packages.debian.org/bookworm/libglx-mesa0][libglx-mesa0]] need to be installed to enable rendering previews for Markdown files or OpenAPI specifications.

2. Download latest release files from https://www.jetbrains.com/idea/download/?section=linux:
   #+name: idea_download
   #+begin_src shell :results silent
     IDEA_INSTALLATION_FILE=ideaIU-2024.3.3.tar.gz
     curl -O --output-dir /tmp \
	  "https://download-cdn.jetbrains.com/idea/$IDEA_INSTALLATION_FILE{,.sha256}"
   #+end_src

3. Verify checksum:
   #+name: idea_verify
   #+begin_src shell :results silent
     grep $(sha256sum /tmp/$IDEA_INSTALLATION_FILE | cut -d ' ' -f 1) \
	  /tmp/$IDEA_INSTALLATION_FILE.sha256
   #+end_src

4. Extract binary:
   #+name: idea_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$IDEA_INSTALLATION_FILE
   #+end_src

5. Create link:
   #+name: idea_create_link
   #+begin_src shell :results silent
     find opt/ -name idea -exec ln -s ~/{} ~/.local/bin/idea \;
   #+end_src

6. Node.js is needed globally at least in version 18.17.0 for the SonarQube plugin:
   #+name: idea_install_nodejs
   #+begin_src shell :results silent
     asdf install nodejs 18.7.0
     asdf set -u nodejs 18.7.0
   #+end_src

** Install Visual Studio Code
1. Install necessary prerequisites for different features:
   #+name: vscode_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y \
	     libgl1
   #+end_src
   [[https://packages.debian.org/bookworm/libgl1][libgl1]] needs to be installed, to preven the following error:
   : Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory

2. Download latest release files from https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions. The version ~latest~ is not supported by the API-URL below, which is needed to get the checksums. Therefore fixed versions are used:
   #+name: vscode_download
   #+begin_src shell :results silent
     VSCODE_VERSION=1.99.3
     VSCODE_INSTALLATION_FILE=code-stable-$VSCODE_VERSION.tar.gz
     curl -L -o /tmp/$VSCODE_INSTALLATION_FILE \
	  "https://update.code.visualstudio.com/$VSCODE_VERSION/linux-x64/stable"
   #+end_src

3. Verify checksum:
   #+name: vscode_verify
   #+begin_src shell :results silent
     curl "https://update.code.visualstudio.com/api/versions/$VSCODE_VERSION/linux-x64/stable" |
	 grep $(sha256sum /tmp/$VSCODE_INSTALLATION_FILE | cut -d ' ' -f 1)
   #+end_src

4. Extract binary:
   #+name: vscode_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$VSCODE_INSTALLATION_FILE
   #+end_src

5. Create link:
   #+name: vscode_create_link
   #+begin_src shell :results silent
     ln -s ~/opt/VSCode-linux-x64/code ~/.local/bin/code
   #+end_src

** Install PlantUML
1. Install [[https://packages.debian.org/bookworm/graphviz][graphviz]], which is necessary for some diagrams, as described at https://plantuml.com/en/graphviz-dot:
   #+name: plantuml_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y graphviz
   #+end_src

2. Import GPG-Key of user id /plantuml@gmail.com/ having the key id /019586D44BD80213/ and the fingerprint /C08C18EE1706DB378BD993C8019586D44BD80213/:
   *Note*: Must be done before, once
   #+begin_src shell results silent
     gpg --recv-keys 019586D44BD80213
   #+end_src

3. Sign and mark as non-exportable without user interaction.
   *Note*: This only works, if the signing key is present! And must be done before
   #+begin_src shell results silent
     gpg --quick-lsign-key C08C18EE1706DB378BD993C8019586D44BD80213 plantuml@gmail.com
   #+end_src

4. Download the desired version of the GPL release from [[https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions][https://plantuml.com/en/download]], to have the most features supported. Also download the corresponding signature:
   #+name: plantuml_download
   #+begin_src shell :results silent
     PLANTUML_VERSION=1.2025.3
     PLANTUML_INSTALLATION_FILE=plantuml-$PLANTUML_VERSION.jar
     mkdir -p ~/opt
     curl -L -O --output-dir ~/opt \
	  "https://github.com/plantuml/plantuml/releases/download/v$PLANTUML_VERSION/$PLANTUML_INSTALLATION_FILE{,.asc}"
   #+end_src

5. Verify the installation file:
   #+name: plantuml_verify
   #+begin_src shell
     gpg --verify ~/opt/$PLANTUML_INSTALLATION_FILE.asc
   #+end_src

   should result something like:
   : gpg: assuming signed data in '/home/kunde/opt/plantuml-1.2025.3.jar'
   : gpg: Signature made Sun 01 Jun 2025 11:18:54 AM CEST
   : gpg:                using RSA key 019586D44BD80213
   : gpg: Good signature from "PlantUML JAR Signing Key <plantuml@gmail.com>" [full]

6. Delete signature:
   #+name: plantuml_remove_signature
   #+begin_src shell :results silent
     rm  ~/opt/$PLANTUML_INSTALLATION_FILE.asc
   #+end_src

7. Create link:
   #+name: plantuml_create_link
   #+begin_src shell :results silent
     ln -fs ~/opt/$PLANTUML_INSTALLATION_FILE ~/opt/plantuml.jar
   #+end_src

8. To verify installation, execute:
   #+begin_src shell :results verbatim
     java -jar ~/opt/plantuml.jar -testdot
   #+end_src

   should result something like:
   : Dot version: dot - graphviz version 2.43.0 (0)
   : Installation seems OK. File generation OK

