#+title: WSL 2 configuration
#+author: Aaron Kunde
#+email: aaron.kunde@web.de
Settings and descriptions of the WSL 2 configuration.

This project describes the configuration of the WSL 2 and scripts to set up this configuration.

* Prerequisites
It is assumed, that an official [[https://github.com/microsoft/WSL/releases][release]] is initially installed and the default user is not /root/. This configuration is tested on a Debian (bookworm) distribution with the WSL version 2.4.11.0. This version should also support [[https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][Linux GUI apps]].

* Configure WSL Debian
To automate the configuration the script [[file:bin/config_debian.sh][config_debian.sh]] includes all necessary steps, which has to be executed by root.
#+begin_src shell :tangle bin/config_debian.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<apt_disable_recs>>
  <<apt_add_non-free>>
  <<alternatives_set_editor>>
  <<locale_install_de>>

  <<apt_update>>
  <<install_global_base_software>>
  <<install_global_latex>>

  <<purge_docker_and_podman>>
  <<install_podman>>
  <<install_podman-compose>>

  <<install_global_python-requirements>>
#+end_src

** Disable recommended packages
Regarding [[https://wiki.debian.org/ReduceDebian#Reconfigure_apt_so_that_it_does_not_install_additional_packages][Reduce Debian]], reconfigure /apt/ so that it does not install additional packages, by adding a new file ~/etc/apt/apt.conf.d/10get~:

#+name: apt_disable_recs
#+begin_src shell :dir /sudo:: :results silent
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10get
#+end_src

To verify, execution of
#+begin_src shell :results verbatim
  apt-config dump | grep -e 'APT::Install-'
#+end_src

should return:
: APT::Install-Recommends "0";
: APT::Install-Suggests "0";

** Add non-free packages
To install non-free packages (like /emacs-common-non-dfsg/), add a file ~/etc/apt/sources.list.d/debian.non-free.list~:
#+name: apt_add_non-free
#+begin_src shell :dir /sudo:: :results silent
  sed /etc/apt/sources.list -e \
      's/\(deb.* \)main/\1non-free non-free-firmware/' \
      | tee /etc/apt/sources.list.d/debian.non-free.list
#+end_src

and update APT by executing
#+name: apt_update
#+begin_src shell :dir /sudo:: :results silent
  apt-get update
#+end_src
afterwards.

** Set default editor
Based on  https://wiki.debian.org/TextEditor set the default editor globally to the already installed /vim.tiny/:
#+name: alternatives_set_editor
#+begin_src shell :dir /sudo:: :results silent
  update-alternatives --set editor /usr/bin/vim.tiny
#+end_src

To verify, execution of
#+begin_src shell :results verbatim
  update-alternatives --display editor | grep current
#+end_src

should result to:
:   link currently points to /usr/bin/vim.tiny

** Add needed locales
To use /de_DE.UTF-8/ in other programs, like Emacs, these additional locales must at least be installed, like it is described at https://wiki.debian.org/Locale:
#+name: locale_install_de
#+begin_src shell :dir /sudo:: :results verbatim
  sed -iorig -e 's/# de_DE\.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  locale-gen
#+end_src

** OPTIONAL: Set locale for scripts                                :optional:
Like it is described in the [[https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Locale-Environment-Variables.html][gettext manual]] and at https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do, scripts use the variable ~LC_ALL~, which should be set as a fallback. For now the default is /en_EN.UTF-8/ is used.

** Install global software
Install software for every day use:
#+name: install_global_base_software
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  aspell-de \
	  bash-completion \
	  ca-certificates \
	  curl \
	  dos2unix \
	  emacs \
	  emacs-common-non-dfsg \
	  file \
	  git \
	  gitk \
	  gnupg \
	  gnuplot \
	  man-db \
	  net-tools \
	  netcat-openbsd \
	  markdown \
	  openssh-client \
	  patch
#+end_src

Install packages for working with LaTeX. Emacs is already installed or will be as a dependency:
#+name: install_global_latex
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  auctex \
	  texlive-latex-recommended \
	  texlive-latex-extra \
	  texlive-plain-generic
#+end_src

** Activate systemd                                                :obsolete:
To use Podman or Docker properly, /systemctl/ is needed. Therefore the [[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/][systemd support on WSL]] has to be activated. Because in newer versions (WSL version: 2.3.26.0) this is already done, the following steps should not be needed:

1. Create a file in the WSL ~/etc/wsl.conf~, if not already exists:
#+begin_src shell :dir /sudo:: :results silent
  echo -e "[boot]\nsystemd=true" > /etc/wsl.conf
#+end_src

2. Restart WSL
#+begin_src powershell
  wsl --shutdown
#+end_src

3. To check, if ~systemctl~ works, executing
#+begin_src shell :results verbatim
  systemctl list-unit-files --type=service
#+end_src

should result in something like:
#+begin_example
  UNIT FILE                              STATE           PRESET
  apt-daily-upgrade.service              static          -
  ...
  x11-common.service                     masked          enabled

  115 unit files listed.
#+end_example

*Note*: To have systemctl working for non-root users, /dbus-user-session/ must be installed and running. It is not installed as default, but comes as a dependency of /podman/ or /gnupg/. After installation of /dbus-user-session/, it may be necessary to terminate WSL with:
#+begin_src powershell
  wsl --terminate <<Distro>>
#+end_src

** Install Podman 4.3.1

*** Deinstall old versions
If an older version of podman or docker is installed, it should be purged:
#+name: purge_docker_and_podman
#+begin_src shell :dir /sudo:: :results silent
  apt-get purge -y \
	  docker \
	  docker-compose \
	  containernetworking-plugins \
	  podman \
	  podman-compose
  apt-get autopurge -y
#+end_src

*** Install Podman
Based on https://podman.io/docs/installation, install podman and its necessary dependencies:
#+name: install_podman
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman
  apt-get install --mark-auto \
	  uidmap \
	  slirp4netns
#+end_src

*** Verify
Based on https://docs.podman.io/en/latest/Introduction.html, execution of
#+begin_src shell :results verbatim
  podman run docker.io/library/busybox echo "hey there"
#+end_src

should restult in:
: hey there

** Use docker-compose files
There are several alternatives to use Docker Compose files together with Podman:
1. [[* Use Podman Compose 1.0.3][Use Podman Compose]]
2. [[* OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman][Use Docker Compose]]
3. Use Podman Pods and generate Kubernetes files, like described on https://www.redhat.com/en/blog/compose-podman-pods

*** Use Podman Compose 1.0.3
This is based on https://github.com/containers/podman-compose. Since this is the simpliest and nearest method to Podman, it is also the preferred one, even if it is not fully compatible with all features of Docker Compose.
To Install Podman Compose, just execute:
#+name: install_podman-compose
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman-compose
#+end_src

*** OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman       :optional:
Based on  https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/, this setup can be used to use the ~docker-compose~ command. This may be necessary, if features unsupported by ~podman-compose~ are needed. This may lead to side-effects with networking.

1. Verify, that Podman socket is active by executing
   #+begin_src shell :results verbatim
      systemctl status podman.socket
   #+end_src

   which should result to something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/lib/systemd/system/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Mon 2025-02-17 08:59:30 CET; 2 days ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/podman/podman.sock (Stream)
	  CGroup: /system.slice/podman.socket

     Feb 17 08:59:30 6RBVJR3 systemd[1]: Listening on podman.socket - Podman API Socket.
   #+end_example

2. Install /docker-compose/ and /podman-docker/ as dependency:
   #+begin_src shell :dir /sudo:: :results silent
       apt-get install -y docker-compose
       apt-get install -y --mark-auto podman-docker
   #+end_src

3. Verify the communication with the Docker socket by executing:
   #+begin_src shell :dir /sudo:: :results verbatim
     curl -H "Content-Type: application/json" --unix-socket /var/run/docker.sock http://localhost/_ping
   #+end_src

   This should result to:
   : OK

4. Start Podman socket for regular user:
   #+begin_src shell :results silent
     systemctl --user enable podman.socket
     systemctl --user start podman.socket
   #+end_src

   Verify the creation of the socket, by executing
   #+begin_src shell :results verbatim
     systemctl --user status podman.socket
   #+end_src

   which should return something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Wed 2025-02-19 17:10:37 CET; 7s ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/user/1000/podman/podman.sock (Stream)
	  CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

     Feb 19 17:10:37 6RBVJR3 systemd[205]: Listening on podman.socket - Podman API Socket.
   #+end_example

5. Verify by executing ~docker-compose~ after setting the environment variable ~DOCKER_HOST~
   #+begin_src shell
     DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock docker-compose up
   #+end_src

*** TODO Needed for init containers
#+begin_src shell
  sudo apt-get install catatonit
#+end_src

*** TODO Later dependencies for podman
#+begin_src shell
  netavark aardvark-dns
  buildah
  +dbus-user-session+
  fuse-overlayfs
  catatonit
#+end_src

*** TODO Stuff to docker-compose
https://github.com/containers/podman-compose/blob/devel/README.md
https://docs.oracle.com/en/learn/podman-compose/index.html
https://github.com/containers/podman/issues/13396
https://www.redhat.com/sysadmin/container-networking-podman
https://github.com/containers/podman/pull/17578
https://github.com/containers/podman/issues/17499
https://github.com/containers/podman/issues/17731
Wird benötigt, wenn Features von docker-compose benötigt werden, die nicht von Podman compose unterstützt werden. Kann aber zu Nebeneffekten bei Netzwerken führen, da hierduch CNI als Default-Netzwerk-Backend gesetzt wird, was wiederum nicht dem Podman-Reinen default von netavark.

*** TODO OBSOLETE: Setup for Debian WSL2 Podman 3.x                :obsolete:
https://gist.github.com/GiovanniGrieco/94ab72099fa35bc307fda0e36b88f1bd
#+begin_src sh
  mkdir -p $HOME/.config/containers/ &&
  sed -e 's/.*cgroup_manager =.*/cgroup_manager = "cgroupfs"/' /usr/share/containers/containers.conf | sed -e 's/.*events_logger = .*/events_logger = "file"/' > ~/.config/containers/containers.conf
#+end_src


*** TODO Networking-Probleme
https://github.com/containers/podman-compose/issues/541#issuecomment-1221417067

* Configure user environment
#+begin_src shell :tangle bin/config_user.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<gpg_add_tty>>

  <<ssh_add_start_ssh-agent_to_profile>>
  <<ssh_add_config>>

  <<firefox_create_link>>

  <<asdf_download>>
  <<asdf_verify>>
  <<asdf_extract>>
  <<asdf_add_shims>>
  <<asdf_add_shell_completions>>

  <<kubectl_install>>
  <<kubectl_add_shell_completions>>

  <<helm_install>>
  <<helm_add_shell_completions>>

  <<make_install>>

  <<python_install>>

  <<azure-cli_install>>

  <<idea_download>>
  <<idea_verify>>
  <<idea_extract>>
  <<idea_create_link>>
#+end_src

** Configure GPG
To enable signing of git commits using the commandline, add the following configuration to ~$HOME/.profile~ like it is described in the [[https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html#Invoking-GPG_002dAGENT][GnuPG manual:]]
#+name: gpg_add_tty
#+begin_src shell :results silent
  echo -e '\nexport GPG_TTY=$(tty)' >> ~/.profile
#+end_src

** Configure SSH agent
Based on https://www.ssh.com/academy/ssh/agent, the SSH agent should be either started by adding
#+begin_src shell
  eval $(ssh-agent)
#+end_src
to ~$HOME/.profile~ or by using the provided ~/etc/X11/Xsession.d/90x11-common_ssh-agent~ for a system-wide start. Both ways are not suitable for WSL, because the first creates a new agent for each terminal and the latter does not work, because ~Xsession~ is never executed.

Therefore, based on https://superuser.com/questions/1808572/how-to-automate-starting-the-ssh-agent-and-adding-my-keys-in-wsl2-for-windows, the following lines are added to ~$HOME/profile~
#+begin_src shell :tangle bin/start_ssh-agent.sh :mkdirp yes :noweb yes
  SSH_AGENT_ENV_FILE=.ssh/agent-env

  if [ -z "$(pidof ssh-agent)" ]; then
      ssh-agent | head -n2 > $SSH_AGENT_ENV_FILE
  fi
  if [ -f $SSH_AGENT_ENV_FILE ]; then
      eval $(cat $SSH_AGENT_ENV_FILE)
  fi
#+end_src

by executing:
#+name: ssh_add_start_ssh-agent_to_profile
#+begin_src shell :results silent
  echo '' >> ~/.profile
  cat bin/start_ssh-agent.sh >> ~/.profile
#+end_src

Another option could be, to use /systemd/ as user by by executing:
#+begin_src shell
  systemctl --user start ssh-agent
#+end_src
But this is not a suitable solution, because it does not set the necessary environment variables ~SSH_AUTH_SOCK~ in the current or a new terminal.

To always instruct a running SSH agent to add keys, add the following configuration setting to your local ssh config file ~$HOME/.ssh/config~ before any ~Host~ or ~Match~ restrictions. Otherwise it will only be activated for this condition. Here it is set as the first option:
#+name: ssh_add_config
#+begin_src shell :results silent
  echo 'AddKeysToAgent yes' > ~/.ssh/config
#+end_src

** Create link to Firefox
To use the Firefox, which is installed on the host system, create the following link in =~/.local/bin/=:
#+name: firefox_create_link
#+begin_src shell
  mkdir -p ~/.local/bin
  ln -fs "/mnt/c/Users/$USER/AppData/Local/Microsoft/WindowsApps/firefox.exe" \
     ~/.local/bin/firefox
#+end_src

** Install asdf
Based on [[https://asdf-vm.com/guide/getting-started.html][asdf Getting started]] /Download Pre-compiled binary/:

1. Download latest release files from https://github.com/asdf-vm/asdf/releases:
   #+name: asdf_download
   #+begin_src shell :results silent
     ASDF_VERSION=v0.16.4
     ASDF_INSTALLATION_FILE=asdf-$ASDF_VERSION-linux-amd64.tar.gz
     curl -L -O --output-dir /tmp \
	  "https://github.com/asdf-vm/asdf/releases/download/$ASDF_VERSION/$ASDF_INSTALLATION_FILE{,.md5}"
   #+end_src

2. Verify checksum:
   #+name: asdf_verify
   #+begin_src shell :results silent
     grep $(md5sum /tmp/$ASDF_INSTALLATION_FILE | cut -d ' ' -f 1) /tmp/$ASDF_INSTALLATION_FILE.md5
   #+end_src

3. Extract binary:
   #+name: asdf_extract
   #+begin_src shell :results silent
     mkdir -p ~/.local/bin
     tar -C ~/.local/bin -x -f /tmp/$ASDF_INSTALLATION_FILE
   #+end_src

4. Verify installation. After relogin executing
   #+begin_src shell :results verbatim
     type -a asdf
   #+end_src

   should result to:
   : asdf is /home/kunde/.local/bin/asdf

5. The asdf shims directory must be added to ~PATH~:
   #+name: asdf_add_shims
   #+begin_src shell :results silent
     echo -e '\nPATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"' >> ~/.profile
   #+end_src

6. To add shell completion, add a line this to ~$HOME/.bashrc~:
   #+name: asdf_add_shell_completions
   #+begin_src shell :results silent
     echo -e '\n. <(asdf completion bash)' >> ~/.bashrc
   #+end_src

** Install asdf (legacy)                                           :obsolete:
Based on [[https://asdf-vm.com/guide/getting-started-legacy.html][asdf Getting started (pre-0.16.0)]]:

1. Checkout latest release:
   #+begin_src shell :results silent
       git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.15.0
   #+end_src

2. Add script to ~$PATH~ and Bash completions:
   #+begin_src shell :results silent
     echo -e '\n. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
     echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc
  #+end_src

3. To take effect, relogin or create a new subshell

** Configure asdf
Create a configuration file ~$HOME/.asdfrc~, to support versions files used by other version managers:
   #+name: asdf_create_config
   #+begin_src shell
     echo 'legacy_version_file = yes' > ~/.asdfrc
   #+end_src

** Install kubectl
1. To install the latest version of kubectl using asdf, execute:
   #+name: kubectl_install
   #+begin_src shell :results silent
     asdf plugin add kubectl
     asdf install kubectl latest
     asdf set -u kubectl latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     kubectl version
   #+end_src

   Which should return something like:
   : Client Version: v1.32.1
   : Kustomize Version: v5.5.0
   : Server Version: v1.31.4+rke2r1

3. Install autocompletion for bash. Based on https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/, add a line to ~$HOME/.bashrc~:
   #+name: kubectl_add_shell_completions
   #+begin_src shell :results silent
     echo -e '\n. <(kubectl completion bash)' >> ~/.bashrc
   #+end_src

** Install Helm
1. To install the latest version of helm using asdf, execute:
   #+name: helm_install
   #+begin_src shell :results silent
     asdf plugin add helm
     asdf install helm latest
     asdf set -u helm latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     helm version
   #+end_src

   Which should return something like:
   : version.BuildInfo{Version:"v3.17.1", GitCommit:"980d8ac1939e39138101364400756af2bdee1da5", GitTreeState:"clean", GoVersion:"go1.23.5"}

3. Install autocompletion for bash. Based on https://helm.sh/docs/helm/helm_completion_bash/#helm, add a line to ~$HOME/.bashrc~:
   #+name: helm_add_shell_completions
   #+begin_src shell :results silent
     echo -e '\n. <(helm completion bash)' >> ~/.bashrc
   #+end_src

** Install make
1. To install the latest version of make using asdf, execute:
   #+name: make_install
   #+begin_src shell :results silent
     asdf plugin add make
     asdf install make latest
     asdf set -u make latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     make -v
   #+end_src

   Which should return something like:
   : GNU Make 4.4.1
   : Built for x86_64-pc-linux-gnu
   : Copyright (C) 1988-2023 Free Software Foundation, Inc.
   : License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
   : This is free software: you are free to change and redistribute it.
   : There is NO WARRANTY, to the extent permitted by law.

** Install Python 3.11
1. Python needs some system-wide packages installed, which are described at https://github.com/pyenv/pyenv/wiki#suggested-build-environment:
   #+name: install_global_python-requirements
   #+begin_src shell :dir /sudo::
     apt-get install -y \
	     gcc \
	     zlib1g-dev \
	     libssl-dev
   #+end_src

   *Note*: These are the minimum required packages, to complete the installation. For later use, further packages may be needed.

2. Furthermore, [[* Install make][make]] needs to be installed, which can be done using asdf.

3. After that, Python 3.11.11 can be installed using asdf by executing:
   #+name: python_install
   #+begin_src shell :results silent
     asdf plugin add python
     asdf install python 3.11.11
     asdf set -u python 3.11.11
   #+end_src

4. Verify installation by executing:
   #+begin_src shell :results verbatim
     python --version
   #+end_src

   Which should return:
   : Python 3.11.11

** Install Azure CLI
1. Before installing Azure CLI, a version of [[* Install Python 3.11][Python]] must be installed, which can be done using asdf.

2. To install the latest version of azure-cli using asdf, execute:
   #+name: azure-cli_install
   #+begin_src shell :results silent
     asdf plugin add azure-cli
     asdf install azure-cli latest
     asdf set -u azure-cli latest
   #+end_src

3. Verify installation by executing:
   #+begin_src shell :results verbatim
     az version
   #+end_src

   Which should return something like:
   : {
   :   "azure-cli": "2.68.0",
   :   "azure-cli-core": "2.68.0",
   :   "azure-cli-telemetry": "1.1.0",
   :   "extensions": {}
   : }

** Install IntelliJ
1. Download latest release files from https://www.jetbrains.com/idea/download/?section=linux:
   #+name: idea_download
   #+begin_src shell :results silent
     IDEA_INSTALLATION_FILE=ideaIU-2024.3.3.tar.gz
     curl -O --output-dir /tmp \
	  "https://download-cdn.jetbrains.com/idea/$IDEA_INSTALLATION_FILE{,.sha256}"
   #+end_src

2. Verify checksum:
   #+name: idea_verify
   #+begin_src shell :results silent
     grep $(sha256sum /tmp/$IDEA_INSTALLATION_FILE | cut -d ' ' -f 1) /tmp/$IDEA_INSTALLATION_FILE.sha256
   #+end_src

3. Extract binary:
   #+name: idea_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$IDEA_INSTALLATION_FILE
   #+end_src

4. Create link:
   #+name: idea_create_link
   #+begin_src shell :results silent
     mkdir -p ~/opt
     find opt/ -name idea -exec ln -s ~/{} ~/.local/bin/idea \;
   #+end_src

** Install minikube                                                    :fail:
1. To install the latest version of minikube using asdf, execute:
   #+name: minikube_install
   #+begin_src shell :results silent
     asdf plugin add minikube
     asdf install minikube latest
   #+end_src

2. Verify installation by executing:
   #+begin_src shell :results verbatim
     minikube version
   #+end_src

   Which should return something like
   #+begin_example
     No version is set for command minikube
     Consider adding one of the following versions in your config file at /home/kunde/.tool-versions
     minikube 1.35.0
   #+end_example

3. The actual used version of minikube is project specific and not set globally. It is determined locally by an existing ~.tool-versions~. To use latest minikube together with Podman rootless execute the following in the project:
   #+begin_src shell
     asdf set minikube latest
     minikube config set rootless true
   #+end_src

4. After that, minikube might be used in the project with:
   #+begin_src shell
     minikube start
   #+end_src

   *Note*: Actually minikube in combination with podman rootless and WSL 2 Debian does not work and leads to the folling errors and warnings:
   #+begin_example
     The minimum required version for podman is "4.9.0". your version is "4.3.1". minikube might not work. use at your own risk.
     ...
     stderr:
	     [WARNING Swap]: swap is supported for cgroup v2 only. The kubelet must be properly configured to use swap. Please refer to https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory, or disable swap on the node
	     [WARNING SystemVerification]: cgroups v1 support is in maintenance mode, please migrate to cgroups v2
	     [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
     error execution phase wait-control-plane: could not initialize a Kubernetes cluster
     ...
   #+end_example
** TODO Basic SD
#+begin_src

#+end_src
#+begin_src shell :results verbatim
apt-cache show \


	     xz-utils \

	     unzip 
#+end_src

** TODO Weiteres für Entwicklung
#+begin_src shell
  apt-mark showauto \


	 gimp \
	 # To prevent error: https://stackoverflow.com/questions/17355863/cant-find-install-libxtst-so-6 \
	 libxtst6 \
	 # Maybe because of plantuml
	 graphviz \
	 bzip2 \

	 # for IntelliJ \
	 libdrm2 \
	 libgbm1 \
	 # To prevent error messages. See: https://gist.github.com/jeffcogswell/62395900725acef1c0a5a608f7eb7a05 \
	 at-spi2-core \
	 # To prevent error messages. See: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo \
	 libgl1-mesa-glx \

#+end_src

#+RESULTS:




