#+title: WSL 2 configuration
#+author: Aaron Kunde
#+email: aaron.kunde@web.de
Settings and descriptions of the WSL 2 configuration.

This project describes the configuration of the WSL 2 and scripts to set up this configuration.

* Prerequisites
It is assumed, that an official [[https://github.com/microsoft/WSL/releases][release]] is initially installed and the default user is not /root/. This configuration is tested on a Debian (bookworm) distribution with the WSL version 2.4.11.0. This version should also support [[https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][Linux GUI apps]].

* Configuration
To automate the configuration the script [[file:bin/config_debian.sh][config_debian.sh]] includes all necessary steps, which has to be executed by root.
#+begin_src shell :tangle bin/config_debian.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<apt_disable_recs>>
  <<apt_add_non-free>>
  <<alternatives_set_editor>>
  <<locale_install_de>>

  <<apt_update>>
  <<install_global_base_software>>
  <<install_global_latex>>

  <<purge_docker_and_podman>>
  <<install_podman>>
#+end_src

** Disable recommended packages
Regarding [[https://wiki.debian.org/ReduceDebian#Reconfigure_apt_so_that_it_does_not_install_additional_packages][Reduce Debian]], reconfigure /apt/ so that it does not install additional packages, by adding a new file ~/etc/apt/apt.conf.d/10get~:

#+name: apt_disable_recs
#+begin_src shell :dir /sudo:: :results silent
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10get
#+end_src

To verify, execution of
#+begin_src shell :results verbatim
  apt-config dump | grep -e 'APT::Install-'
#+end_src

should return:
: APT::Install-Recommends "0";
: APT::Install-Suggests "0";

** Add non-free packages
To install non-free packages (like /emacs-common-non-dfsg/), add a file ~/etc/apt/sources.list.d/debian.non-free.list~:
#+name: apt_add_non-free
#+begin_src shell :dir /sudo:: :results silent
  sed /etc/apt/sources.list -e \
      's/\(deb.* \)main/\1non-free non-free-firmware/' \
      | tee /etc/apt/sources.list.d/debian.non-free.list
#+end_src

and update APT by executing
#+name: apt_update
#+begin_src shell :dir /sudo:: :results silent
  apt-get update
#+end_src
afterwards.

** Set default editor
Based on  https://wiki.debian.org/TextEditor set the default editor globally to the already installed /vim.tiny/:
#+name: alternatives_set_editor
#+begin_src shell :dir /sudo:: :results silent
  update-alternatives --set editor /usr/bin/vim.tiny
#+end_src

To verify, execution of
#+begin_src shell :results verbatim
  update-alternatives --display editor | grep current
#+end_src

should result to:
:   link currently points to /usr/bin/vim.tiny

** Add needed locales
To use /de_DE.UTF-8/ in other programs, like Emacs, these additional locales must at least be installed, like it is described at https://wiki.debian.org/Locale:
#+name: locale_install_de
#+begin_src shell :dir /sudo:: :results verbatim
  sed -iorig -e 's/# de_DE\.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  locale-gen
#+end_src

** OPTIONAL: Set locale for scripts                                :optional:
Like it is described in the [[https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Locale-Environment-Variables.html][gettext manual]] and at https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do, scripts use the variable ~LC_ALL~, which should be set as a fallback. For now the default is /en_EN.UTF-8/ is used.

** Install global software
Install software for every day use:
#+name: install_global_base_software
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  aspell-de \
	  bash-completion \
	  ca-certificates \
	  curl \
	  dos2unix \
	  emacs \
	  emacs-common-non-dfsg \
	  file \
	  git \
	  gitk \
	  gnupg \
	  gnuplot \
	  man-db \
	  net-tools \
	  netcat-openbsd \
	  markdown \
	  openssh-client \
	  patch
#+end_src

Install packages for working with LaTeX. Emacs is already installed or will be as a dependency:
#+name: install_global_latex
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  auctex \
	  texlive-latex-recommended \
	  texlive-latex-extra \
	  texlive-plain-generic
#+end_src

** Activate systemd                                                :obsolete:
To use Podman or Docker properly, /systemctl/ is needed. Therefore the [[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/][systemd support on WSL]] has to be activated. Because in newer versions (WSL version: 2.3.26.0) this is already done, the following steps should not be needed:

1. Create a file in the WSL ~/etc/wsl.conf~, if not already exists:
#+begin_src shell :dir /sudo:: :results silent
  echo -e "[boot]\nsystemd=true" > /etc/wsl.conf
#+end_src

2. Restart WSL
#+begin_src powershell
  wsl --shutdown
#+end_src

3. To check, if ~systemctl~ works, executing
#+begin_src shell :results verbatim
  systemctl list-unit-files --type=service
#+end_src

should result in something like:
#+begin_example
  UNIT FILE                              STATE           PRESET
  apt-daily-upgrade.service              static          -
  ...
  x11-common.service                     masked          enabled

  115 unit files listed.
#+end_example

*Note*: To have systemctl working for non-root users, /dbus-user-session/ must be installed and running. It is not installed as default, but comes as a dependency of /podman/ or /gnupg/. After installation of /dbus-user-session/, it may be necessary to terminate WSL with:
#+begin_src powershell
  wsl --terminate <<Distro>>
#+end_src

** Install Podman 4.3.1

*** Deinstall old versions
If an older version of podman or docker is installed, it should be purged:
#+name: purge_docker_and_podman
#+begin_src shell :dir /sudo:: :results silent
  apt-get purge -y \
	  docker \
	  docker-compose \
	  containernetworking-plugins \
	  podman \
	  podman-compose
  apt-get autopurge -y
#+end_src

*** Install Podman
Based on https://podman.io/docs/installation, install podman and its necessary dependencies:
#+name: install_podman
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman
  apt-get install --mark-auto \
	  uidmap \
	  slirp4netns
#+end_src

*** Verify
Based on https://docs.podman.io/en/latest/Introduction.html, execution of
#+begin_src shell :results verbatim
  podman run docker.io/library/busybox echo "hey there"
#+end_src

should restult in:
: hey there
#+begin_src shell
  sudo apt-get purge docker podman podman-compose docker-compose containernetworking-plugins
#+end_src

*** TODO Installation
Based on https://podman.io/docs/installation, install podman with its recommended packages, which are needed for a smooth experience:
#+begin_src shell
  sudo apt-get install --install-recommends podman
#+end_src

**** Install Dependencies
Install new network stack for Podman >= 4, if not installed automatically:
#+begin_src shell
   sudo apt-get install netavark aardvark-dns
#+end_src
