# -*- eval: (flyspell-mode) -*-
:PROPERTIES:
:header-args: :results verbatim
:END:
#+title: WSL 2 configuration
#+author: Aaron Kunde
#+email: aaron.kunde@web.de

Settings and descriptions of the WSL 2 configuration.

This project describes the configuration of the WSL 2 and scripts to set up this configuration.

* Prerequisites
It is assumed, that an official [[https://github.com/microsoft/WSL/releases][release]] is initially installed and the default user is not /root/. This configuration is tested on a Debian (bookworm) distribution with the WSL version 2.4.11.0. This version should also support [[https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][Linux GUI apps]].

* Configure WSL Debian
To automate the configuration the script [[file:~/work/config-wsl/bin/config_debian.sh][config_debian.sh]] includes all necessary steps, which has to be executed as /root/.
#+begin_src shell :tangle ../bin/config_debian.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  <<apt_disable_recs>>
  <<apt_add_non-free>>
  <<alternatives_set_editor>>
  <<locale_install_de>>

  <<systemd_install_dbus-user-session>>

  <<podman_purge_old_versions>>
  <<podman_install_global_requirements>>
  <<podman_install>>
  <<podman_install_rootless_requirements>>
  <<podman-compose_install>>

  <<nct_install_requirements>>
  <<nct_add_gpg-key>>
  <<nct_add_apt-sources>>
  <<nct_install>>
  <<nct_configure_podman>>

  <<install_global_base_software>>

  <<gpg_install_pinentry-x11>>

  <<latex_install>>

  <<python_install_requirements>>

  <<gradle_install_requirements>>

  <<idea_install_requirements>>

  <<vscode_install_requirements>>

  <<plantuml_install_requirements>>
#+end_src

** Disable recommended packages
Regarding [[https://wiki.debian.org/ReduceDebian#Reconfigure_apt_so_that_it_does_not_install_additional_packages][Reduce Debian]], configure APT to not install additional packages. Add a new file ~/etc/apt/apt.conf.d/10get~:
#+name: apt_disable_recs
#+begin_src shell :dir /sudo:: :results silent
  echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/10get
#+end_src

To verify, execute:
#+begin_src shell
  apt-config dump | grep -e 'APT::Install-'
#+end_src

This should result to:
: APT::Install-Recommends "0";
: APT::Install-Suggests "0";

** Add non-free packages
To install non-free packages, like [[https://packages.debian.org/bookworm/emacs-common-non-dfsg][emacs-common-non-dfsg]], add a file =/etc/apt/sources.list.d/debian.non-free.list= and update APT:
#+name: apt_add_non-free
#+begin_src shell :dir /sudo:: :results silent
  sed /etc/apt/sources.list -e \
      's/\(deb.* \)main/\1non-free non-free-firmware/' \
      > /etc/apt/sources.list.d/debian.non-free.list
  apt-get update
#+end_src

** Set default editor
Based on  https://wiki.debian.org/TextEditor set the default editor globally to the already installed [[https://packages.debian.org/bookworm/vim-tiny][vim.tiny]]:
#+name: alternatives_set_editor
#+begin_src shell :dir /sudo:: :results silent
  update-alternatives --set editor /usr/bin/vim.tiny
#+end_src

To verify, execute:
#+begin_src shell
  update-alternatives --display editor | grep current
#+end_src

This should result to:
:   link currently points to /usr/bin/vim.tiny

** Add needed locales
The default locale in WSL is determined by the locale of the Windows installation. This can be determined by executing in the powershell:
#+begin_src powershell
  Get-WinSystemLocale
#+end_src

This should return something like:
: LCID             Name             DisplayName
: ----             ----             -----------
: 1033             en-US            English (United States)

The default locale should be /en_US.UTF-8/. The current locale of the WSL can be determined by executing:
#+begin_src shell
  locale
#+end_src

This should then result to:
#+begin_example
  LANG=en_US.UTF-8
  LANGUAGE=
  LC_CTYPE="en_US.UTF-8"
  LC_NUMERIC="en_US.UTF-8"
  LC_TIME="en_US.UTF-8"
  LC_COLLATE="en_US.UTF-8"
  LC_MONETARY="en_US.UTF-8"
  LC_MESSAGES="en_US.UTF-8"
  LC_PAPER="en_US.UTF-8"
  LC_NAME="en_US.UTF-8"
  LC_ADDRESS="en_US.UTF-8"
  LC_TELEPHONE="en_US.UTF-8"
  LC_MEASUREMENT="en_US.UTF-8"
  LC_IDENTIFICATION="en_US.UTF-8"
  LC_ALL=
#+end_example

To use the additional locale /de_DE.UTF-8/ in other programs (like Emacs), it must be installed, like it is described at https://wiki.debian.org/Locale:
#+name: locale_install_de
#+begin_src shell :dir /sudo::
  sed -i.orig -e 's/# de_DE\.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  locale-gen
#+end_src

** OPTIONAL: Set locale for scripts                                :optional:
Like it is described in the [[https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Locale-Environment-Variables.html][gettext manual]] and at https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do, scripts use the variable ~LC_ALL~, which should be set as a fallback. For now, the default /en_EN.UTF-8/ is used.

** Activate systemd
To use Podman or Docker properly, [[https://packages.debian.org/bookworm/systemctl][systemctl]] is needed. Therefore the [[https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/][systemd support on WSL]] has to be activated. The current Debian distribution already contains a file =/etc/wsl.conf= with the needed entry to enable systemctl.

Executing
#+begin_src shell
  grep  -e '\[boot\]' -e 'systemd=true' /etc/wsl.conf
#+end_src

should result to something like:
: [boot]
: systemd=true

If the file is missing, follow these steps:
1. Create a file ~/etc/wsl.conf~, if not already exists:
   #+begin_src shell :dir /sudo:: :results silent
     echo -e "[boot]\nsystemd=true" > /etc/wsl.conf
   #+end_src

2. After creating the file, WSL needs to be restarted:
   #+begin_src powershell
     wsl --shutdown
   #+end_src

3. [[https://packages.debian.org/bookworm/dbus-user-session][dbus-user-session]] should be installed to have systemctl work properly and avoid error messages like the following:
   : wsl: Failed to start the systemd user session for 'root'. See journalctl for more details.

   It is also needed to have Podman function properly. Which it why it comes as a dependency of [[https://packages.debian.org/bookworm/podman][podman]] or [[https://packages.debian.org/bookworm/gnupg][gnupg]]:
   #+name: systemd_install_dbus-user-session
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y dbus-user-session
   #+end_src

4. The WSL has to be terminated to have the installation of dbus-user-session take effect:
   #+begin_src powershell
     wsl --terminate
   #+end_src

5. To verify, if ~systemctl~ works, execute:
   #+begin_src shell
     systemctl list-unit-files --type=service
   #+end_src

   This should result to something like:
   #+begin_example
     UNIT FILE                              STATE           PRESET
     apt-daily-upgrade.service              static          -
     ...
     x11-common.service                     masked          enabled

     115 unit files listed.
   #+end_example

   *Note*: If more than one distribution is installed, the following error might still occur after logging into the distro:
   : wsl: Failed to start the systemd user session for 'kunde'. See journalctl for more details.
   and executing ~podman ps~ might result to something like:
   #+begin_example
     WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available
     WARN[0000] For using systemd, you may need to login using an user session
     WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
     WARN[0000] Falling back to --cgroup-manager=cgroupfs
     WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available
     WARN[0000] For using systemd, you may need to login using an user session
     WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
     WARN[0000] Falling back to --cgroup-manager=cgroupfs
     CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
   #+end_example
   This seems to be an open issue within WSL: https://github.com/microsoft/WSL/issues/13826

** Install Podman 4.3.1
The current version of Podman in the current Debian stable distribution is 4.3.1.

*** Deinstall old versions
Based on the [[https://docs.docker.com/engine/install/debian/][Docker installation manual]], uninstall old versions of docker and podman and everything, which might have been installed before:
#+name: podman_purge_old_versions
#+begin_src shell :dir /sudo:: :results silent
  apt-get autopurge -y \
	  '*docker*' \
	  docker-compose \
	  '*container*' \
	  '*podman*' \
	  podman-compose

  rm -rf /var/lib/docker \
     /var/lib/containerd \
     /etc/apt/sources.list.d/docker.list \
     /etc/apt/keyrings/docker.asc \
     /etc/containers
#+end_src

*** Install Podman
Based on https://podman.io/docs/installation, install [[https://packages.debian.org/bookworm/podman][podman]] and its necessary dependencies:

1. Some packages are required to have Podman function properly, like:
   - [[https://packages.debian.org/bookworm/aardvark-dns][aardvark-dns]] :: Necessary for creating networks and for DNS resolution inside networks between containers.
   - [[https://packages.debian.org/bookworm/ca-certificates][ca-certificates]] :: Needed to install the necessary certificates for downloading and using images.
   - [[https://packages.debian.org/bookworm/dbus-user-session][dbus-user-session]] :: Like mentioned in [[* Activate systemd][systemd activation]], this package is needed even for root mode, to have Podman work properly. Otherwise the following error occurs after pod creation:
     : Error: crun: cannot open sd-bus: No such file or directory: OCI runtime attempted to invoke a command that was not found
   - [[https://packages.debian.org/bookworm/iptables][iptables]] :: Needed by [[https://packages.debian.org/bookworm/netavark][netavark]] to create firewall rules. If not present, the following error occurs:
     : Error: netavark (exit code 1): No such file or directory (os error 2)
   #+name: podman_install_global_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y --mark-auto \
	     aardvark-dns \
	     ca-certificates \
	     dbus-user-session \
	     iptables
   #+end_src

2. After that podman can be installed:
   #+name: podman_install
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y podman
   #+end_src

*** Enable rootless environment
Based on the [[https://github.com/containers/podman/blob/v4.3.1/docs/tutorials/rootless_tutorial.md][Podman rootless tutorial]], several packages need to be installed:
- [[https://packages.debian.org/bookworm/uidmap][uidmap]] :: To use Podman without errors in userspace, providing =newuidmap=.
- [[https://packages.debian.org/bookworm/slirp4netns][slirp4netns]] :: To use Podman in userspace without errors, providing =slirp4netns= (see: [[https://github.com/containers/podman/blob/v4.3/docs/tutorials/basic_networking.md#differences-between-rootful-and-rootless-container-networking][Differences between rootful and rootless container networking]]).
  *Note*: According to https://podman.io/docs/installation, ~slirp4netns~ is not needed in newer versions of Podman anymore.
#+name: podman_install_rootless_requirements
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y --mark-auto \
	  uidmap \
	  slirp4netns
#+end_src

*Note*: According to https://www.redhat.com/en/blog/podman-rootless-overlay, [[https://packages.debian.org/bookworm/fuse-overlayfs][fuse-overlayfs]] is not needed in newer versions of Podman anymore and is therefore not installed.

*** Verify installation
The installation for root and rootless environment can then be verified with:
#+begin_src shell
  whoami
  mkdir -p ~/tst_dir
  podman network create tst_nw

  podman run --name=sink --net tst_nw \
	 -v ~/tst_dir:/container/volume \
	 -d \
	 docker.io/subfuzion/netcat -k -l -p 1111

  podman run --name=source -d --net tst_nw \
	 --entrypoint '["sh", "-c", "echo \"Hello Podman\" | nc sink 1111"]' \
	 docker.io/subfuzion/netcat

  podman logs sink

  podman exec sink whoami
  podman exec sink touch /container/volume/test
  podman exec sink ls -l /container/volume/test
  ls -l ~/tst_dir

  podman rm -f sink source
  podman network rm tst_nw

  rm -rf ~/tst_dir
#+end_src

This should result to something like:
#+begin_example
  kunde
  tst_nw
  3ac6082a65e9153458028c2a7759f483fc4a93f898d55edf0a165b22906585ec
  96a35d90787aee88dc4346006284699f72c78afd4e84d180139a7565aa6049d5
  root
  -rw-r--r--    1 root     root             0 Apr  2 10:11 /container/volume/test
  total 0
  -rw-r--r-- 1 kunde kunde 0 Apr  2 12:11 test
  sink
  source
  tst_nw
#+end_example

** Use docker-compose files
There are several alternatives to use Docker Compose files together with Podman:
1. [[* Use Podman Compose 1.0.3][Use Podman Compose]]
2. [[* OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman][Use Docker Compose]]
3. Use Podman Pods and generate Kubernetes files, like described on https://www.redhat.com/en/blog/compose-podman-pods

*** Use Podman Compose 1.0.3
This is based on https://github.com/containers/podman-compose. Since this is the simplest and nearest method to Podman, it is also the preferred one, even if it is not fully compatible with all features of Docker Compose.
To install [[https://packages.debian.org/bookworm/podman-compose][podman-compose]], execute:
#+name: podman-compose_install
#+begin_src shell :dir /sudo:: :results silent
  apt-get install -y podman-compose
#+end_src

*** OPTIONAL: Use Docker Compose 1.29.2 with rootless Podman       :optional:
Based on  https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/, this setup can be used to use the ~docker-compose~ command. This may be necessary, if features unsupported by Podman Compose are needed. This may lead to side-effects with networking.

1. Verify, that Podman socket is active:
   #+begin_src shell
      systemctl status podman.socket
   #+end_src

   This should result to something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/lib/systemd/system/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Mon 2025-02-17 08:59:30 CET; 2 days ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/podman/podman.sock (Stream)
	  CGroup: /system.slice/podman.socket

     Feb 17 08:59:30 6RBVJR3 systemd[1]: Listening on podman.socket - Podman API Socket.
   #+end_example

2. Install [[https://packages.debian.org/bookworm/docker-compose][docker-compose]] and [[https://packages.debian.org/bookworm/podman-docker][podman-docker]] as dependency:
   #+begin_src shell :dir /sudo:: :results silent
       apt-get install -y docker-compose
       apt-get install -y --mark-auto podman-docker
   #+end_src

3. Verify the communication with the Docker socket:
   #+begin_src shell :dir /sudo::
     curl -H "Content-Type: application/json" --unix-socket /var/run/docker.sock http://localhost/_ping
   #+end_src

   This should result to:
   : OK

4. Start Podman socket for regular user:
   #+begin_src shell :results silent
     systemctl --user enable podman.socket
     systemctl --user start podman.socket
   #+end_src

   Verify the creation of the socket:
   #+begin_src shell
     systemctl --user status podman.socket
   #+end_src

   This should return something like:
   #+begin_example
     ● podman.socket - Podman API Socket
	  Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: enabled)
	  Active: active (listening) since Wed 2025-02-19 17:10:37 CET; 7s ago
	Triggers: ● podman.service
	    Docs: man:podman-system-service(1)
	  Listen: /run/user/1000/podman/podman.sock (Stream)
	  CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

     Feb 19 17:10:37 6RBVJR3 systemd[205]: Listening on podman.socket - Podman API Socket.
   #+end_example

5. Verify by executing ~docker-compose~ after setting the environment variable ~DOCKER_HOST~
   #+begin_src shell
     DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock docker-compose up
   #+end_src

** Install NVIDIA Container Toolkit 1.19.0-1
To give Podman containers access to the NVIDIA GPU, the [[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/index.html][NVIDIA Container Toolkit]] must be installed, like described for the [[https://hub.docker.com/r/ollama/ollama][Ollama Docker image]]:

1. Install curl to proceed with the installation:
   #+name: nct_install_requirements
   #+begin_src shell :results silent :dir /sudo::
     apt-get install -y --mark-auto curl
   #+end_src

2. Download the GPG keys and add them to the keyring as ~/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg~:
   #+name: nct_add_gpg-key
   #+begin_src shell :results silent :dir /sudo::
     curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
	 | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
   #+end_src

3. Add the sources for the toolkit as ~/etc/apt/sources.list.d/nvidia-container-toolkit.list~ to APT and update APT:
   #+name: nct_add_apt-sources
   #+begin_src  shell :results silent :dir /sudo::
     curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
	 | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
	 > /etc/apt/sources.list.d/nvidia-container-toolkit.list
     apt-get update
   #+end_src

5. Install the toolkit, based on [[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html][installation guide]]:
   #+name: nct_install
   #+begin_src shell :results silent :dir /sudo::
     apt-get install -y nvidia-container-toolkit
   #+end_src

   Verify the installation:
   #+begin_src shell
     nvidia-ctk -v
   #+end_src

   This should result to:
   : NVIDIA Container Toolkit CLI version 1.19.0
   : commit: ec7b4e2fa2caecad6d89be4a26029b831fe7503a

6. Currently, the automatic configuration of [[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html][CDI support]] does not trigger, because several conditions in =/etc/systemd/system/nvidia-cdi-refresh.service=, like path to =nvidia-smi= or modules, do not match on WSL. Therefore, Podman must be configured by adding a permanent CDI specification (=/etc/cdi/nvidia.yaml=) manually, like described for [[https://podman-desktop.io/docs/podman/gpu][Podman Desktop]]:
   #+name: nct_configure_podman
   #+begin_src shell :results silent :dir /sudo::
     nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
   #+end_src

   Verify the configuration, by executing =nvidia-smi= inside a container:
   #+begin_src shell
     nvidia-ctk cdi list
     podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable \
	    ubuntu nvidia-smi -L
   #+end_src

   This should result to something like:
   : nvidia.com/gpu=all
   : GPU 0: NVIDIA RTX A1000 Laptop GPU (UUID: GPU-67d3f5e6-b6f8-ecd8-b874-106d2fc38caf)

** Install additional software
Install software for every day use:
#+name: install_global_base_software
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  aspell-de \
	  bash-completion \
	  btop \
	  curl \
	  dos2unix \
	  emacs \
	  emacs-common-non-dfsg \
	  file \
	  git \
	  gitk \
	  gnupg \
	  gnuplot \
	  htop \
	  lsof \
	  man-db \
	  net-tools \
	  netcat-openbsd \
	  markdown \
	  openssh-client \
	  patch \
	  telnet \
	  xorriso \
	  xz-utils
#+end_src

Install packages for working with LaTeX. Emacs is already installed or will be as a dependency:
#+name: latex_install
#+begin_src shell :dir /sudo::
  apt-get install -y \
	  auctex \
	  texlive-latex-recommended \
	  texlive-latex-extra \
	  texlive-plain-generic
#+end_src

* OPTIONAL: Restore user directory from backup                     :optional:
It might be necessary, to restore the user directory from the [[file:backup.org::Restore user directory][backup]], before configuring the user environment:
#+begin_src shell
  ../bin/restore_user.sh
#+end_src

* Configure user environment
The script [[file:~/work/config-wsl/bin/config_user.sh][config_user.sh]] includes all necessary steps, to setup the user environment. It has to be executed as a non-root user. The path =$HOME/.local/bin= is only added to =PATH=, if the directory exists. Because this is not the case, when executing this script initially, =$HOME/.local/bin= is added for this script execution explicitly:
#+begin_src shell :tangle ../bin/config_user.sh :mkdirp yes :noweb yes :shebang "#!/bin/sh" :exports none
  set -e

  if [ "$(id -u)" -eq 0 ]; then
      echo "You should not be root"
      exit 1
  fi

  cp /etc/skel/.profile ~
  cp /etc/skel/.bashrc ~

  PATH="$HOME/.local/bin:$PATH"

  <<disable_at-spi2-error>>

  <<gpg_add_tty>>

  <<ssh_add_start_ssh-agent_to_profile>>
  <<ssh_add_config>>

  <<firefox_create_link>>

  <<asdf_download>>
  <<asdf_verify>>
  <<asdf_extract>>
  <<asdf_add_shims>>
  <<asdf_add_shell_completions>>
  <<asdf_create_config>>

  <<direnv_install>>
  <<direnv_hook_into_shell>>
  <<direnv_config_accept_env>>

  <<kubectl_install>>
  <<kubectl_add_shell_completions>>

  <<helm_install>>
  <<helm_add_shell_completions>>

  <<helm-docs_install>>

  <<helm-schema_install>>

  <<make_install>>

  <<shellcheck_install>>

  <<python_install>>

  <<uv_install>>

  <<azure-cli_install>>

  <<golang_install>>

  <<java_install>>

  <<maven_install>>

  <<gradle_install>>

  <<nodejs_install>>

  <<pnpm_install>>

  <<lua_install>>

  <<idea_download>>
  <<idea_verify>>
  <<idea_extract>>
  <<idea_create_link>>

  <<dbeaver_download>>
  <<dbeaver_verify>>
  <<dbeaver_extract>>
  <<dbeaver_create_link>>

  <<vscode_download>>
  <<vscode_verify>>
  <<vscode_extract>>
  <<vscode_create_link>>

  <<plantuml_fetch_gpg-key>>
  <<plantuml_download>>
  <<plantuml_verify>>
  <<plantuml_remove_signature>>
  <<plantuml_create_link>>

  <<pandoc_install>>
  <<pandoc_add_shell_completions>>

  <<testcontainers_config>>
  <<testcontainers_disable_ryuk>>

  <<mermaid_install>>
  <<mermaid_add_link>>

  <<aider_install>>

  <<k6_install>>

  <<opencode_install>>
  <<opencode_add_link>>

  <<trivy_install>>

  <<openspec_install>>
  <<openspec_add_link>>
#+end_src

** Disable AP-SPI warning message
GTK applications display the following error message, if the package [[https://packages.debian.org/at-spi2-core][at-spi2-core]] is not installed:
: ... dbind-WARNING ... AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Since no accessibility is needed the package is not installed. The error message is disabled by setting the environment variable ~NO_AT_BRIDGE=1~ in ~$HOME/.profile~:
#+name: disable_at-spi2-error
#+begin_src shell :results silent
  printf '\nexport NO_AT_BRIDGE=1\n' >> ~/.profile
#+end_src

** Configure GPG
To enable signing and encryption using the command line, add the following configuration to ~$HOME/.profile~ like it is described in the [[https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html#Invoking-GPG_002dAGENT][GnuPG manual:]]
#+name: gpg_add_tty
#+begin_src shell :results silent
  printf '\nexport GPG_TTY=$(tty)\n' >> ~/.profile
#+end_src

** Install pinentry for X11
The default pinentry ([[https://packages.debian.org/pinentry-curses][pinentry-curses]]) does work in the terminal, but not within Emacs [[https://magit.vc/][Magit]]. As a workaround, a pinentry, which provides pinentry-x11 is installed:
#+name: gpg_install_pinentry-x11
#+begin_src shell :results silent :dir /sudo::
  apt-get install -y pinentry-fltk
#+end_src

** Configure SSH agent
Based on https://www.ssh.com/academy/ssh/agent, the SSH agent should be either started by adding
#+begin_src shell
  eval $(ssh-agent)
#+end_src
to ~$HOME/.profile~ or by using the provided ~/etc/X11/Xsession.d/90x11-common_ssh-agent~ for a system-wide start. Both ways are not suitable for WSL, because the first creates a new agent for each terminal and the latter does not work, because ~Xsession~ is never executed.

Therefore, based on https://superuser.com/questions/1808572/how-to-automate-starting-the-ssh-agent-and-adding-my-keys-in-wsl2-for-windows, the following lines are added to ~$HOME/profile~
#+name: start_ssh-agent.sh
#+begin_src shell
  SSH_AGENT_ENV_FILE="$HOME/.ssh/agent-env"

  if [ -z "$(pidof ssh-agent)" ]; then
      ssh-agent | head -n2 > $SSH_AGENT_ENV_FILE
  fi
  if [ -f $SSH_AGENT_ENV_FILE ]; then
      eval $(cat $SSH_AGENT_ENV_FILE)
  fi
#+end_src

by executing:
#+name: ssh_add_start_ssh-agent_to_profile
#+begin_src shell :noweb yes :exports none :results silent
  cat <<'EOF' >> ~/.profile

  <<start_ssh-agent.sh>>
  EOF
#+end_src

Another option could be, to use [[https://packages.debian.org/bookworm/systemd][systemd]] as user by by executing:
#+begin_src shell
  systemctl --user start ssh-agent
#+end_src
But this is not a suitable solution, because it does not set the necessary environment variables ~SSH_AUTH_SOCK~ in the current or a new terminal.

To always instruct a running SSH agent to add keys, add the following configuration setting to your local ssh config file ~$HOME/.ssh/config~ before any ~Host~ or ~Match~ restrictions. Otherwise it will only be activated for this condition. Here it is set as the first option:
#+name: ssh_add_config
#+begin_src shell :results silent
  mkdir -p ~/.ssh
  echo 'AddKeysToAgent yes' > ~/.ssh/config
#+end_src

** Create link to Firefox
To use the Firefox, which is installed on the host system, create the following link in =~/.local/bin/=:
#+name: firefox_create_link
#+begin_src shell
  mkdir -p ~/.local/bin
  ln -fs "/mnt/c/Users/$USER/AppData/Local/Microsoft/WindowsApps/firefox.exe" \
     ~/.local/bin/firefox
#+end_src

** Install asdf
Based on [[https://asdf-vm.com/guide/getting-started.html][asdf Getting started]], using the Method /Download Pre-compiled binary/:

1. Download latest release files from [[https://github.com/asdf-vm/asdf/releases][asdf releases]]:
   #+name: asdf_download
   #+begin_src shell :results silent
     ASDF_VERSION=v0.16.4
     ASDF_INSTALLATION_FILE=asdf-$ASDF_VERSION-linux-amd64.tar.gz
     curl -L -O --output-dir /tmp \
	  "https://github.com/asdf-vm/asdf/releases/download/$ASDF_VERSION/$ASDF_INSTALLATION_FILE{,.md5}"
   #+end_src

2. Verify checksum:
   #+name: asdf_verify
   #+begin_src shell :results silent
     grep "$(md5sum /tmp/$ASDF_INSTALLATION_FILE | cut -d ' ' -f 1)" \
	  /tmp/$ASDF_INSTALLATION_FILE.md5
   #+end_src

3. Extract binary into =~/.local/bin/=:
   #+name: asdf_extract
   #+begin_src shell :results silent
     mkdir -p ~/.local/bin
     tar -C ~/.local/bin -x -f /tmp/$ASDF_INSTALLATION_FILE
   #+end_src

4. Verify installation. After relogin executing
   #+begin_src shell
     type -a asdf
   #+end_src

   This should result to:
   : asdf is /home/kunde/.local/bin/asdf

5. The asdf shims directory must be added to =PATH= for the current and future sessions:
   #+name: asdf_add_shims
   #+begin_src shell :results silent
     PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
     printf '\nPATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"\n' >> ~/.profile
   #+end_src

6. To add shell completion, add the following line to ~$HOME/.bashrc~:
   #+name: asdf_add_shell_completions
   #+begin_src shell :results silent
     printf '\n. <(~/.local/bin/asdf completion bash)\n' >> ~/.bashrc
   #+end_src
   Since =~/.bashrc= is sourced, before =~/.local/bin= is added to the =PATH= in =~/.profile=, ~asdf~ cannot be called without prefix. So the explicit path to asdf is used.

** Install asdf (legacy)                                           :obsolete:
Based on [[https://asdf-vm.com/guide/getting-started-legacy.html][asdf Getting started (pre-0.16.0)]]:

1. Checkout latest release:
   #+begin_src shell :results silent
     git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.15.0
   #+end_src

2. Add =asdf.sh= to =PATH= and Bash completions:
   #+begin_src shell :results silent
     echo '\n. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
     echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc
  #+end_src

3. To take effect, relogin or create a new subshell

** Configure asdf
Create a configuration file =$HOME/.asdfrc=, to support versions files used by other version managers:
   #+name: asdf_create_config
   #+begin_src shell
     echo 'legacy_version_file = yes' > ~/.asdfrc
   #+end_src

** Install direnv
For many configurations, [[https://direnv.net/][direnv]] is very useful. In general, the latest version of direnv is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of kubectl with asdf:
   #+name: direnv_install
   #+begin_src shell :results silent
     asdf plugin add direnv
     asdf install direnv latest
     asdf set -u direnv latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     direnv --version
   #+end_src

   This should result to something like:
   : 2.37.1

3. [[https://direnv.net/docs/hook.html][Hook]] direnv into the shell:
   #+name: direnv_hook_into_shell
   #+begin_src shell :results silent
     printf '\neval "$(direnv hook bash)"\n' >> ~/.profile
   #+end_src

4. Configure direnv by its [[https://direnv.net/man/direnv.toml.1.html][configuration file]] =$HOME/.config/direnv/direnv.toml= to accept =.env= files:
   #+name: direnv_config_accept_env
   #+begin_src shell :results silent
     mkdir -p ~/.config/direnv
     printf '[global]\nload_dotenv = true\n' > ~/.config/direnv/direnv.toml
   #+end_src

** Install kubectl
In general, the latest version of [[https://kubernetes.io/docs/reference/kubectl/][kubectl]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of kubectl with asdf:
   #+name: kubectl_install
   #+begin_src shell :results silent
     asdf plugin add kubectl
     asdf install kubectl latest
     asdf set -u kubectl latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     kubectl version
   #+end_src

   This should result to something like:
   : Client Version: v1.32.1
   : Kustomize Version: v5.5.0
   : Server Version: v1.31.4+rke2r1

3. Install autocompletion for bash. Based on [[https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/][Install bash-completion]], add a line to =$HOME/.profile=:
   #+name: kubectl_add_shell_completions
   #+begin_src shell :results silent
     printf '\n. <(kubectl completion bash)\n' >> ~/.profile
   #+end_src

   *Note*: =~/.bashrc= is sourced before =~/.asdf/shims= is added to the =PATH= in =~/.profile=. The shim =~/.asdf/shims/kubectl= itself uses the command ~asdf~ without a prefix. Therefore the shim cannot be used within =~/.bashrc=. As a workaround, the completion is sourced in =~/.profile=, until the shims may be fixed.

** Install Helm 3.17.1
In general, the latest version of [[https://helm.sh/][Helm]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. The keyword ~latest~ is currently not supported by the asdf plugin. Therefore, a specific version of Helm is installed:
   #+name: helm_install
   #+begin_src shell :results silent
     asdf plugin add helm
     asdf install helm 3.17.1
     asdf set -u helm 3.17.1
   #+end_src

2. Verify installation:
   #+begin_src shell
     helm version
   #+end_src

   This should result to something like:
   : version.BuildInfo{Version:"v3.17.1", GitCommit:"980d8ac1939e39138101364400756af2bdee1da5", GitTreeState:"clean", GoVersion:"go1.23.5"}

3. Install autocompletion for bash. Based on [[https://helm.sh/docs/helm/helm_completion_bash/#helm][helm completion bash]], add a line to =$HOME/.profile=:
   #+name: helm_add_shell_completions
   #+begin_src shell :results silent
     printf '\n. <(helm completion bash)\n' >> ~/.profile
   #+end_src

   *Note*: =~/.bashrc= is sourced before =~/.asdf/shims= is added to the =PATH= in =~/.profile=. The shim =~/.asdf/shims/kubectl= itself uses the command ~asdf~ without a prefix. Therefore the shim cannot be used within =~/.bashrc=. As a workaround, the completion is sourced in =~/.profile=, until the shims may be fixed.

** Install helm-docs
Like [[* Install Helm][Helm]], the latest version of [[https://github.com/norwoodj/helm-docs][helm-docs]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:
1. Add the asdf plugin and install the latest version of helm-docs with asdf:
   #+name: helm-docs_install
   #+begin_src shell :results silent
     asdf plugin add helm-docs
     asdf install helm-docs latest
     asdf set -u helm-docs latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     helm-docs --version
   #+end_src

   This should result to something like:
   : helm-docs version 1.14.2

** Install helm-schema
Like [[* Install Helm][Helm]], the latest version of [[https://github.com/dadav/helm-schema][helm-schema]] is used for all projects as a default.

1. Installed as a plugin into the current Helm installation:
   #+name: helm-schema_install
   #+begin_src shell :results silent
     helm plugin install https://github.com/dadav/helm-schema
   #+end_src

** Install make
In general, the latest version of [[https://www.gnu.org/software/make/][GNU make]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of make with asdf:
   #+name: make_install
   #+begin_src shell :results silent
     asdf plugin add make
     asdf install make latest
     asdf set -u make latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     make -v
   #+end_src

   This should result to something like:
   : GNU Make 4.4.1
   : Built for x86_64-pc-linux-gnu
   : Copyright (C) 1988-2023 Free Software Foundation, Inc.
   : License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
   : This is free software: you are free to change and redistribute it.
   : There is NO WARRANTY, to the extent permitted by law.

** Install ShellCheck
In general, the latest version of [[https://www.shellcheck.net/][ShellCheck]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of ShellCheck with asdf:
   #+name: shellcheck_install
   #+begin_src shell :results silent
     asdf plugin add shellcheck
     asdf install shellcheck latest
     asdf set -u shellcheck latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     shellcheck --version
   #+end_src

   This should result to something like:
   : ShellCheck - shell script analysis tool
   : version: 0.10.0
   : license: GNU General Public License, version 3
   : website: https://www.shellcheck.net

** Install Python 3.10.11
The actual used version of [[https://www.python.org/][Python]] may be project specific. But at least one version of Python greater or equal than 3.10.11 is needed globally. It may be overridden for specific projects by an existing =.tool-versions=:

1. Python needs some system-wide packages installed, which are described at https://github.com/pyenv/pyenv/wiki#suggested-build-environment:
   #+name: python_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y \
	     gcc \
	     zlib1g-dev \
	     libssl-dev
   #+end_src

   *Note*: These are the minimum required packages, to complete the installation. For later use, further packages may be needed.

2. Install [[* Install make][make]], which can be done using asdf.

3. Add the asdf plugin and install Python 3.10.11:
   #+name: python_install
   #+begin_src shell :results silent
     asdf plugin add python
     asdf install python 3.10.11
     asdf set -u python 3.10.11
   #+end_src

4. Verify installation:
   #+begin_src shell
     python --version
   #+end_src

   This should result to:
   : Python 3.10.11

** Install uv
In general, the latest version of [[https://docs.astral.sh/uv/][uv]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of Maven with asdf:
   #+name: uv_install
   #+begin_src shell :results silent
     asdf plugin add uv
     asdf install uv latest
     asdf set -u uv latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     uv --version
   #+end_src

   This should result to something like:
   : uv 0.10.9

** Install Azure CLI
In general, the latest version of [[https://learn.microsoft.com/en-us/cli/azure/][Azure CLI]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=. At this moment, at least Python 3.10.11 is needed for an installation.

1. Verify, Python is installed at least at version 3.10.11:
   #+begin_src shell
     python --version
   #+end_src

   This should result to something like:
   : Python 3.10.11

2. Add the asdf plugin and install the latest version of Azure CLI with asdf:
   #+name: azure-cli_install
   #+begin_src shell :results silent
     asdf plugin add azure-cli
     asdf install azure-cli latest
     asdf set -u azure-cli latest
   #+end_src

3. Verify installation:
   #+begin_src shell
     az version
   #+end_src

   This should result to something like:
   : {
   :   "azure-cli": "2.68.0",
   :   "azure-cli-core": "2.68.0",
   :   "azure-cli-telemetry": "1.1.0",
   :   "extensions": {}
   : }

** Install minikube                                                    :fail:
In general, the latest version of [[https://minikube.sigs.k8s.io/][minikube]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of minikube with asdf:
   #+name: minikube_install
   #+begin_src shell :results silent
     asdf plugin add minikube
     asdf install minikube latest
     asdf set -u minikube latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     minikube version
   #+end_src

   This should result to something like
   : minikube version: v1.35.0
   : commit: dd5d320e41b5451cdf3c01891bc4e13d189586ed-dirty

3. Configure minikube to use it together with Podman rootless:
   #+name: minikube_config
   #+begin_src shell :results silent
     minikube config set rootless true
   #+end_src

4. Start minikube:
   #+begin_src shell :results silent
     minikube start
   #+end_src

   *Note*: Actually minikube in combination with podman rootless and WSL 2 Debian does not work and leads to the folling errors and warnings:
   #+begin_example
     The minimum required version for podman is "4.9.0". your version is "4.3.1". minikube might not work. use at your own risk.
     ...
     stderr:
	     [WARNING Swap]: swap is supported for cgroup v2 only. The kubelet must be properly configured to use swap. Please refer to https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory, or disable swap on the node
	     [WARNING SystemVerification]: cgroups v1 support is in maintenance mode, please migrate to cgroups v2
	     [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
     error execution phase wait-control-plane: could not initialize a Kubernetes cluster
     ...
   #+end_example

** Install Go
The actual used version of [[https://go.dev/][Go]] is project specific and not set globally. It is determined locally by an existing =go.mod= or =.tool-versions=:

1. Add the asdf plugin:
   #+name: golang_install
   #+begin_src shell :results silent
     asdf plugin add golang
   #+end_src

2. Install the desired version of Go locally in the project:
   #+begin_src shell :results silent
     asdf install golang latest
   #+end_src

3. Verify installation in the project:
   #+begin_src shell
     go version
   #+end_src

   This should result to something like:
   :  No version is set for command go
   :  Consider adding one of the following versions in your config file at /home/kunde/work/tst-keycloak/.tool-versions
   :  golang 1.24.0

** Install Java 21.0.5
The actual used version of a [[https://www.java.com/][Java]] JDK may be project specific. Because at leat one JRE is needed globally, the current LTS is defined globally:

1. Add the asdf plugin and install a LTS version of the JRE with asdf:
   #+name: java_install
   #+begin_src shell :results silent
     asdf plugin add java
     asdf install java temurin-jre-21.0.5+11.0.LTS
     asdf set -u java temurin-jre-21.0.5+11.0.LTS
   #+end_src

2. Verify installation:
   #+begin_src shell
     java --version
   #+end_src

   This should result to:
   : openjdk 21.0.5 2024-10-15 LTS
   : OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
   : OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

** Install Maven
In general, the latest version of [[https://maven.apache.org/][Maven]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of Maven with asdf:
   #+name: maven_install
   #+begin_src shell :results silent
     asdf plugin add maven
     asdf install maven latest
     asdf set -u maven latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     mvn --version
   #+end_src

   This should result to something like:
   : Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
   : Maven home: /home/kunde/.asdf/installs/maven/3.9.9
   : Java version: 21.0.5, vendor: Eclipse Adoptium, runtime: /home/kunde/.asdf/installs/java/temurin-21.0.5+11.0.LTS
   : Default locale: en_US, platform encoding: UTF-8
   : OS name: "linux", version: "5.15.167.4-microsoft-standard-wsl2", arch: "amd64", family: "unix"

** Install Gradle
The actual used version of [[https://gradle.org/][Gradle]] is project specific and not set globally. It is determined locally by an existing =.tool-versions=:

1. Add the asdf plugin:
   #+name: gradle_install
   #+begin_src shell :results silent
     asdf plugin add gradle
   #+end_src

2. Install [[https://packages.debian.org/bookworm/unzip][unzip]] as a necessary prerequisite for the Gradle installation:
   #+name: gradle_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y unzip
   #+end_src

3. Install the desired version of Gradle locally in the project. The keyword ~latest~ is currently not supported by the asdf plugin. Therefore, a specific version of Gradle must be installed:
   #+begin_src shell :results silent
     asdf install gradle 8.12
   #+end_src

4. Verify installation in the project:
   #+begin_src shell
     gradle --version
   #+end_src

   This should result to something like:
   : gradle 8.12

** Install Node.js 22.22.0
The actual used version of [[https://nodejs.org/en][Node.js]] may be project specific. At least one version of Node.js greater or equal than 22.22.0 is needed globally for several tools. So the version 22.22.0 is installed and defined globally. It may be overridden for specific projects by an existing =.nvmrc= or =.tool-versions=:

1. Add the asdf plugin:
   #+name: nodejs_install
   #+begin_src shell :results silent
     asdf plugin add nodejs
     asdf install nodejs 22.22.0
     asdf set -u nodejs 22.22.0
   #+end_src

2. Verify installation:
   #+begin_src shell
     node --version
   #+end_src

   This should result to:
   : v22.22.0

** Install pnpm
The actual used version of [[https://pnpm.io/][pnpm]] is project specific and not set globally. It is determined locally by an existing =.tool-versions=.

1. Add the asdf plugin:
   #+name: pnpm_install
   #+begin_src shell :results silent
     asdf plugin add pnpm
   #+end_src

2. Install the desired version of pnpm locally in the project. The version is usually defined in =package.json= and can be determined:
   #+begin_src shell :results silent
     __PNPM_VERSION=$(grep pnpm@ package.json | cut -d'@' -f2 | tr -d '",')
     asdf install pnpm $__PNPM_VERSION
     asdf set pnpm $__PNPM_VERSION
     unset __PNPM_VERSION
   #+end_src

3. Verify installation in the project:
   #+begin_src shell
     pnpm --version
   #+end_src

   This should result to something like:
   : 9.6.0

** Install Pandoc
In general, the latest version of [[https://pandoc.org/][Pandoc]] is used for all projects as a default. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install the latest version of Pandoc with asdf:
   #+name: pandoc_install
   #+begin_src shell :results silent
     asdf plugin add pandoc
     asdf install pandoc latest
     asdf set -u pandoc latest
   #+end_src

2. Verify installation:
   #+begin_src shell
     pandoc --version
   #+end_src

   This should result to something like:
   : pandoc 3.8.2.1
   : Features: +server +lua
   : Scripting engine: Lua 5.4
   : User data directory: /home/kunde/.local/share/pandoc
   : Copyright (C) 2006-2025 John MacFarlane. Web:  https://pandoc.org
   : This is free software; see the source for copying conditions. There is no
   : warranty, not even for merchantability or fitness for a particular purpose.

3. Install autocompletion for bash. Based on [[https://pandoc.org/MANUAL.html][Pandoc User's Guide]], add a line to =$HOME/.profile=:
   #+name: pandoc_add_shell_completions
   #+begin_src shell :results silent
     printf '\n. <(pandoc --bash-completion)\n' >> ~/.profile
   #+end_src

   *Note*: =~/.bashrc= is sourced before =~/.asdf/shims= is added to the =PATH= in =~/.profile=. The shim =~/.asdf/shims/kubectl= itself uses the command ~asdf~ without a prefix. Therefore the shim cannot be used within =~/.bashrc=. As a workaround, the completion is sourced in =~/.profile=, until the shims may be fixed.

** Install Lua 5.4.7
The actual used version of [[https://www.lua.org/][Lua]] may be project specific. Since Lua is used for some global config files, at least one version is needed globally. It may be overridden for specific projects by an existing =.tool-versions=:

1. Add the asdf plugin and install latest Lua version. The current version of luarocks (3.13.0) is broken (see: https://github.com/luarocks/luarocks/issues/1851), so an older version of luarocks is enforced. Since this version does not work with the latest version of Lua (5.5.0), Lua 5.4.7 is enforced:
   #+name: lua_install
   #+begin_src shell :results silent
     asdf plugin add lua
     ASDF_LUA_LUAROCKS_VERSION=3.12.2 asdf install lua 5.4.7
     asdf set -u lua 5.4.7
   #+end_src

2. Verify installation:
   #+begin_src shell
     lua -v
   #+end_src

   This should result to something like:
   : Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio

** Install DBeaver 25.1.0
The latest version can be installed from https://dbeaver.io/download/.

1. Download the specific release files without a JDK from the [[https://github.com/dbeaver/dbeaver/releases][GitHub mirror]], which offers a checksum. Checksums are available since 25.1.0:
   #+name: dbeaver_download
   #+begin_src shell :results silent
     DBEAVER_VERSION=25.1.0
     DBEAVER_INSTALLATION_FILE=dbeaver-ce-$DBEAVER_VERSION-linux.gtk.x86_64-nojdk.tar.gz
     curl -L -O --output-dir /tmp \
	  https://github.com/dbeaver/dbeaver/releases/download/$DBEAVER_VERSION/$DBEAVER_INSTALLATION_FILE
   #+end_src

2. Create a checksum file and verify the installation file:
   #+name: dbeaver_verify
   #+begin_src shell :results silent
     printf '%s %s\n' \
	    '069738a7a58d15d73a9f055e648e131c44f33837cd523d92a2e1203a10c54e49' \
	    /tmp/$DBEAVER_INSTALLATION_FILE > /tmp/$DBEAVER_INSTALLATION_FILE.sha256
     sha256sum -c /tmp/$DBEAVER_INSTALLATION_FILE.sha256
   #+end_src

3. Extract binary:
   #+name: dbeaver_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$DBEAVER_INSTALLATION_FILE
   #+end_src

4. Create link:
   #+name: dbeaver_create_link
   #+begin_src shell :results silent
     mkdir -p ~/.local/bin/
     ln -fs ~/opt/dbeaver/dbeaver ~/.local/bin/dbeaver
   #+end_src

** Install IntelliJ 2024.3.3
1. Install necessary prerequisites for different features:
   - [[https://packages.debian.org/bookworm/libgbm1][libgbm1]] must be installed to enable rendering previews for Markdown files and OpenAPI specifications.
     : cef_server: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
   - [[https://packages.debian.org/bookworm/libgl1][libgl1]] should be installed to prevent the following error:
     : libGL.so.1: cannot open shared object file: No such file or directory
   - [[https://packages.debian.org/bookworm/libnss3][libnss3]] must be installed to enable rendering previews for  Markdown files and to prevent the following error:
     : cef_server: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
   #+name: idea_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y \
	     libgbm1 \
	     libgl1 \
	     libnss3
   #+end_src

2. Download latest release files from https://www.jetbrains.com/idea/download/?section=linux:
   #+name: idea_download
   #+begin_src shell :results silent
     IDEA_INSTALLATION_FILE=ideaIU-2024.3.3.tar.gz
     curl -O --output-dir /tmp \
	  "https://download-cdn.jetbrains.com/idea/$IDEA_INSTALLATION_FILE{,.sha256}"
   #+end_src

3. Verify checksum:
   #+name: idea_verify
   #+begin_src shell :results silent
     grep "$(sha256sum /tmp/$IDEA_INSTALLATION_FILE | cut -d ' ' -f 1)" \
	  /tmp/$IDEA_INSTALLATION_FILE.sha256
   #+end_src

4. Extract binary:
   #+name: idea_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$IDEA_INSTALLATION_FILE
   #+end_src

5. Create link:
   #+name: idea_create_link
   #+begin_src shell :results silent
     find ~/opt -name idea -exec ln -sf {} ~/.local/bin/idea \;
   #+end_src

** Install Visual Studio Code 1.99.3
1. Install necessary prerequisites for different features:
   - [[https://packages.debian.org/bookworm/libgl1][libgl1]] should be installed, to prevent the following error:
     : Could not dlopen libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
   - [[https://packages.debian.org/bookworm/libnss3][libnss3]] must be installed, otherwise Visual Studio Code aborts startup with the following error:
     : code: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
   #+name: vscode_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y \
	     libgl1 \
	     libnss3
   #+end_src

2. Download latest release files from https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions. The version ~latest~ is not supported by the API-URL below, which is needed to get the checksums. Therefore fixed versions are used:
   #+name: vscode_download
   #+begin_src shell :results silent
     VSCODE_VERSION=1.99.3
     VSCODE_INSTALLATION_FILE=code-stable-$VSCODE_VERSION.tar.gz
     curl -L -o /tmp/$VSCODE_INSTALLATION_FILE \
	  "https://update.code.visualstudio.com/$VSCODE_VERSION/linux-x64/stable"
   #+end_src

3. Verify checksum:
   #+name: vscode_verify
   #+begin_src shell :results silent
     curl "https://update.code.visualstudio.com/api/versions/$VSCODE_VERSION/linux-x64/stable" |
	 grep "$(sha256sum /tmp/$VSCODE_INSTALLATION_FILE | cut -d ' ' -f 1)"
   #+end_src

4. Extract binary:
   #+name: vscode_extract
   #+begin_src shell :results silent
     mkdir -p ~/opt
     tar -C ~/opt -x -f /tmp/$VSCODE_INSTALLATION_FILE
   #+end_src

5. Create link:
   #+name: vscode_create_link
   #+begin_src shell :results silent
     mkdir -p ~/.local/bin
     ln -fs ~/opt/VSCode-linux-x64/code ~/.local/bin/code
   #+end_src

** Install PlantUML
1. Install [[https://packages.debian.org/bookworm/graphviz][graphviz]], which is necessary for some diagrams, as described at https://plantuml.com/en/graphviz-dot:
   #+name: plantuml_install_requirements
   #+begin_src shell :dir /sudo:: :results silent
     apt-get install -y graphviz
   #+end_src

2. Import GPG-Key of user id /plantuml@gmail.com/ having the key id /019586D44BD80213/ and the fingerprint /C08C18EE1706DB378BD993C8019586D44BD80213/:
   *Note*: Must be done before, once
   #+name: plantuml_fetch_gpg-key
   #+begin_src shell :results silent
     gpg --recv-keys 019586D44BD80213
   #+end_src

3. Download the desired version of the GPL release from [[https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions][https://plantuml.com/en/download]], to have the most features supported. Also download the corresponding signature:
   #+name: plantuml_download
   #+begin_src shell :results silent
     PLANTUML_VERSION=1.2025.3
     PLANTUML_INSTALLATION_FILE=plantuml-$PLANTUML_VERSION.jar
     mkdir -p ~/opt
     curl -L -O --output-dir ~/opt \
	  "https://github.com/plantuml/plantuml/releases/download/v$PLANTUML_VERSION/$PLANTUML_INSTALLATION_FILE{,.asc}"
   #+end_src

4. Verify the installation file:
   #+name: plantuml_verify
   #+begin_src shell
     gpg --verify ~/opt/$PLANTUML_INSTALLATION_FILE.asc
   #+end_src

   This should result to something like:
   : gpg: assuming signed data in '/home/kunde/opt/plantuml-1.2025.3.jar'
   : gpg: Signature made Sun 01 Jun 2025 11:18:54 AM CEST
   : gpg:                using RSA key 019586D44BD80213
   : gpg: Good signature from "PlantUML JAR Signing Key <plantuml@gmail.com>" [unknown]
   : gpg: WARNING: This key is not certified with a trusted signature!
   : gpg:          There is no indication that the signature belongs to the owner.
   : Primary key fingerprint: C08C 18EE 1706 DB37 8BD9  93C8 0195 86D4 4BD8 0213

   To avoid the warning above, the key can be locally signed and marked as non-exportable:
   #+begin_src shell :results silent
     gpg --quick-lsign-key C08C18EE1706DB378BD993C8019586D44BD80213 plantuml@gmail.com
   #+end_src

   *Note*: This only works, if the signing key is present!

   In this case, the verification above should result to something like:
   : gpg: assuming signed data in '/home/kunde/opt/plantuml-1.2025.3.jar'
   : gpg: Signature made Sun 01 Jun 2025 11:18:54 AM CEST
   : gpg:                using RSA key 019586D44BD80213
   : gpg: Good signature from "PlantUML JAR Signing Key <plantuml@gmail.com>" [full]

5. Delete the signature:
   #+name: plantuml_remove_signature
   #+begin_src shell :results silent
     rm  ~/opt/$PLANTUML_INSTALLATION_FILE.asc
   #+end_src

6. Create a version agnostic link in the installation directory:
   #+name: plantuml_create_link
   #+begin_src shell :results silent
     ln -fs ~/opt/$PLANTUML_INSTALLATION_FILE ~/opt/plantuml.jar
   #+end_src

7. Verify installation:
   #+begin_src shell
     java -jar ~/opt/plantuml.jar -testdot
   #+end_src

   This should result to something like:
   : Dot version: dot - graphviz version 2.43.0 (0)
   : Installation seems OK. File generation OK

** Configure Testcontainers
1. Set socket for Podman. According to [[https://podman-desktop.io/tutorial/testcontainers-with-podman][Testcontainers with Podman]], a file =$HOME/.testcontainers.properties= must be created:
   #+name: testcontainers_config
   #+begin_src shell
     echo docker.host="unix://${XDG_RUNTIME_DIR}/podman/podman.sock" \
	  > "$HOME/.testcontainers.properties"
   #+end_src

   *Note*: If writing the entry without substituting the variable =$XDG_RUNTIME_DIR=, tests in SpringBoot might fail, because the variable is not substituted by default. To avoid this, the value is substituted, as long the directory does not change for the user.

2. Disable [[https://java.testcontainers.org/features/configuration][Ryuk]]. Since Podman is used in rootless mode, Ryuk must be disabled, by setting the following environment ~TESTCONTAINERS_RYUK_DISABLED=true~ in =$HOME/.profile=:
   #+name: testcontainers_disable_ryuk
   #+begin_src shell
     printf '\nexport TESTCONTAINERS_RYUK_DISABLED=true\n' >> ~/.profile
   #+end_src

** Install mermaid-cli
To create images from [[https://mermaid.js.org/][mermaid]] diagrams, [[https://github.com/mermaid-js/mermaid-cli][mermaid-cli]] must be installed. [[* Install Node.js][Node.js]] is required being installed before. 

1. Install mermaid, using [[https://www.npmjs.com/][npm]] into the local installation directory =~/opt/mermaid=:
   #+name: mermaid_install
   #+begin_src shell :results silent
     mkdir -p ~/opt
     npm install -g --prefix ~/opt/mermaid @mermaid-js/mermaid-cli
   #+end_src

2. Create a link to the installed version in =~/.local/bin=, to add =mmdc= to the =PATH=:
   #+name: mermaid_add_link
   #+begin_src shell mermaid_add_link :results silent
     mkdir -p ~/.local/bin
     ln -fs ~/opt/mermaid/bin/mmdc ~/.local/bin/mmdc
   #+end_src

3. Verify installation:
   #+begin_src shell
     mmdc --version
   #+end_src

   This should result to something like:
   : 11.12.0

** Install aider
In general, the latest version of [[https://aider.chat/][aider]] is used for all projects as a default.
According to the [[https://aider.chat/docs/install.html][Installation manual]], at least Python 3.8-3.13  is needed for an installation. The following is based on the [[https://aider.chat/docs/install.html#install-with-uv][installation with uv]]

1. Verify, Python is installed at least at version 3.8:
   #+begin_src shell
     python --version
   #+end_src

   This should result to something like:
   : Python 3.10.11

2. Install aider into =~/opt= with uv, adding a Python 3.13 if needed:
   #+name: aider_install
   #+begin_src shell :results silent
     mkdir -p ~/opt
     UV_TOOL_DIR=~/opt uv tool install --python 3.12 aider-chat@latest
   #+end_src

   This results in:
   - Python 3.12 installed in =~/.local/share/uv/python=
   - aider being installed in =~/opt/aider-chat=
   - A symlink =aider= being installed in =$HOME/.local/bin=

3. Verify installation:
   #+begin_src shell
     aider --version
   #+end_src

   This should result into something like:
   : aider 0.86.1

** Configure aider

*** Add AGENTS.md
Configure aider to use =AGENTS.md=, like it is described on [[https://agents.md/][AGENTS.md]] is done project specific by adding a =.aider.conf.yml=, containing:
#+begin_src yaml
  read: AGENTS.md
#+end_src

** Install OpenCode
1. Following [[https://opencode.ai/docs/de#installation][the installation manual]], using npm. Install OpenCode into the local installation directory =~/opt/opencode=:
   #+name: opencode_install
   #+begin_src shell :results silent
     mkdir -p ~/opt
     npm install -g --prefix ~/opt/opencode opencode-ai
   #+end_src

2. Create a link to the installed version in =~/.local/bin=, to add =opencode= to the =PATH=:
   #+name: opencode_add_link
   #+begin_src shell mermaid_add_link :results silent
     mkdir -p ~/.local/bin
     ln -fs ~/opt/opencode/bin/opencode ~/.local/bin/opencode
   #+end_src

** Install trivy 0.69.3
Because of recent [[https://www.golem.de/news/supply-chain-attacke-trivy-scanner-und-140-npm-pakete-kompromittiert-2603-206808.html][security issues]], a fixed secure version of [[https://trivy.dev/][Trivy]] is used:

The actual used version of [[https://pnpm.io/][pnpm]] is project specific and not set globally. It is determined locally by an existing =.tool-versions=.

1. Add the asdf plugin:
   #+name: trivy_install
   #+begin_src shell :results silent
     asdf plugin add trivy
   #+end_src

2. Install the desired version of pnpm locally in the project. The version is usually defined in =package.json= and can be determined:
   #+begin_src shell :results silent
     asdf install trivy 0.69.3
     asdf set trivy 0.69.3
   #+end_src

3. Verify installation in the project:
   #+begin_src shell
     trivy --version
   #+end_src

   This should result to something like:
   : Version: 0.69.3

** Install OpenSpec
Regarding https://openspec.dev/, OpenSpec needs to be installed globally. [[* Install Node.js][Node.js]] is required being installed before. 

1. Install OpenSpec, using [[https://www.npmjs.com/][npm]] into the local installation directory =~/opt/openspec=:
#+name: openspec_install
#+begin_src shell :results silent
  mkdir -p ~/opt
  npm install -g --prefix ~/opt/openspec @fission-ai/openspec@latest
#+end_src

2. Create a link to the installed version in =~/.local/bin=, to add =openspec= to the =PATH=:
#+name: openspec_add_link
#+begin_src shell :results silent
  mkdir -p ~/.local/bin
  ln -fs ~/opt/openspec/bin/openspec ~/.local/bin/openspec
#+end_src

3. Verify installation:
   #+begin_src shell
     openspec --version
   #+end_src

   This should result to something like:
   : 1.2.0

** Install k6
The actual used version of [[https://k6.io/][k6]] is project specific and not set globally. It is determined locally by an existing =.tool-versions=.

1. Add the asdf plugin:
   #+name: k6_install
   #+begin_src shell :results silent
     asdf plugin add k6
   #+end_src

2. Install the desired version of k6 locally in the project.
   #+begin_src shell :results silent
     asdf install k6 latest
     asdf set k6 latest
   #+end_src

3. Verify installation in the project:
   #+begin_src shell
     k6 --version
   #+end_src

   This should result to something like:
   : k6 v1.6.1 (commit/2ac2bb560e, go1.25.7, linux/amd64)

