#+title: WSL 2 installation
#+author: Aaron Kunde
#+email: aaron.kunde@web.de

The general installation is described at https://github.com/microsoft/WSL and can be done by executing:
#+begin_src powershell
  wsl --install Debian
#+end_src

* Install multiple versions of Debian
To install multiple Debian distros, several options exist:
1. [[#official_distro][Use an official distro]]
2. [[#base_distro][Create and use a base distro]]

** Use an official distro
:PROPERTIES:
:CUSTOM_ID: official_distro
:END:

According to [[https://learn.microsoft.com/en-us/windows/wsl/build-custom-distro][Build a Custom Linux Distribution for WSL]], a ~.wsl~ file is only a ~.tar~ archive, which can be imported with ~wsl -import~.

*** Download a distro
Based on the [[https://learn.microsoft.com/en-us/windows/wsl/install][Offline install]] documentation, the URLs for a ~.wsl~ file can be found in the [[https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json][DistributionInfo.json]].

The official WSL Repo for Debian is mentioned on [[https://wiki.debian.org/InstallingDebianOn/Microsoft/Windows/SubsystemForLinux][the Debian Wiki]] and can be found at [[https://salsa.debian.org/Debian/WSL][WSL Repo on Salsa]]. Version 1.19.0.0 is the oldest [[https://salsa.debian.org/debian/WSL/-/releases][release]], that contains a relatively modern Debian version. According to the [[https://salsa.debian.org/debian/WSL/-/commits/master][commit history]], version 1.19.0.0 contains Debian 12.9, while version 1.22.0.0 contains the first version of Debian trixie (13.0).

The actual ~-wsl~ files can be downloaded from the [[https://salsa.debian.org/debian/WSL/-/releases][releases]]:
#+begin_src powershell
  Invoke-WebRequest `
    -Uri '"https://salsa.debian.org/debian/WSL/-/jobs/7125470/artifacts/raw/Debian_WSL_AMD64_v1.19.0.0.wsl"' `
    -OutFile "$target_dir\Debian_WSL_AMD64_v1.19.0.0.wsl" `
#+end_src

*Note*: The command above does not work, because ~Invoke-WebRequest~ seems to have difficulties with this URL. So download needs to be done with another tool, like a web-browser.

*** Import the new distro
Import the distro as second distro as /Debian-1/ with files at ~%USERPROFILE\Deb-Dir_1%~:
#+begin_src powershell
  wsl --import Debian-1 $env:USERPROFILE\Deb-Dir_1 `
    "$target_dir\Debian_WSL_AMD64_v1.19.0.0.wsl"
#+end_src

*** Create a user
Creation is based on https://learn.microsoft.com/en-en/windows/wsl/build-custom-distro and the [[https://salsa.debian.org/debian/WSL/-/blob/master/linux_files/oobe.sh][oobe.sh]]  of the Debian distribution:
1. Create a user with default UID of 1000. Interaction is only needed to set the password. The username is based on the current username:
   #+begin_src powershell
     wsl -d Debian-1 -u root sh -c "adduser --uid 1000 --quiet --gecos '' $env:USERNAME"
   #+end_src

2. Add the user to the default groups:
   #+begin_src powershell
     wsl -d Debian-1 -u root sh -c "usermod $env:USERNAME -aG 'adm,cdrom,sudo,dip,plugdev'"
   #+end_src

3. Set the default user to the current username:
   #+begin_src powershell
     wsl --manage Debian-1 --set-default-user $env:USERNAME
   #+end_src

** Create and use a base distro
:PROPERTIES:
:CUSTOM_ID: base_distro
:END:

This is an alternate approach, in which a base distro from a fresh installation is reused for multiple versions.

*** Create a base distro
1. After making a backup of your current Debian distro, unregister it:
   #+begin_src powershell
     wsl --unregister Debian
   #+end_src

2. Verify, that no Debian distro exists:
   #+begin_src powershell
     wsl -l
   #+end_src

   This should result to:
   : Windows Subsystem for Linux has no installed distributions.

3. Reinstall a fresh distro.
   #+begin_src powershell
     wsl --install Debian
   #+end_src

4. [[file:backup.org::#backup][Create a backup]] of the fresh Debian distro as base distro:
    #+begin_src powershell
      wsl -d Debian netstat -l
      wsl -d Debian "ps hxo pid | xargs kill"
      wsl --shutdown
      wsl --export Debian "$backup_dir\backup.wsl2.debian.base.tar"
    #+end_src

*** Reimport the base distro
This works like a normal [[file:backup.org::#reimport][reimport]].
1. Remove the new distro:
   #+begin_src powershell
     wsl --unregister Debian-1
   #+end_src

2. Reimport the base distro as second distro /Debian-1/:
   #+begin_src powershell
     wsl --import Debian-1 $env:USERPROFILE\Deb-Dir_1 `
       "$backup_dir\backup.wsl2.debian.base.tar"
   #+end_src

3. Set the default user to the current username:
   #+begin_src powershell
     wsl --manage Debian-1 --set-default-user $env:USERNAME
   #+end_src

* Verify created distros
To verify the distros, execute:
#+begin_src powershell
  wsl -l
#+end_src

This should result to:
: Windows Subsystem for Linux Distributions:
: Debian (Default)
: Debian-1

* Use the new distro
Use the second distro with
#+begin_src powershell
  wsl -d Debian-1
#+end_src

* Fix terminal
After creating a new Terminal, error messages occur, because no icon is set. To fix it, set a proper icon in Terminal. Set Icon to one of the following options:
- Tux :: ~ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png~
- Debian swirl :: ~C:\Users\%USERPROFILE%\Deb-Dir_1\shortcut.ico~

* Run Linux GUI apps
To [[https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps][run Linux GUI apps on the Windows Subsystem for Linux]], an update may be necessary:
#+begin_src powershell
  wsl --update
#+end_src

After that, the WSL has to be restarted:
#+begin_src powershell
  wsl --shutdown
#+end_src
